domain_path: C:\source\.ITA\FPGA\25.2\0.hello\zc702_workspace\zc702_platform\export\zc702_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
