// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_44_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_img_address0,
        input_img_ce0,
        input_img_q0,
        hidden_out_address0,
        hidden_out_ce0,
        hidden_out_we0,
        hidden_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] input_img_address0;
output   input_img_ce0;
input  [31:0] input_img_q0;
output  [9:0] hidden_out_address0;
output   hidden_out_ce0;
output   hidden_out_we0;
output  [6:0] hidden_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln39_fu_255_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [13:0] weights_l1_address0;
wire   [31:0] weights_l1_q0;
wire   [9:0] bn_scale_address0;
wire   [4:0] bn_scale_q0;
wire   [9:0] bn_offset_address0;
wire   [12:0] bn_offset_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln44_fu_273_p2;
reg   [0:0] icmp_ln44_reg_1159;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter1_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter2_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter3_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter4_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter5_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter6_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter7_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter8_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter9_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter10_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter11_reg;
reg   [0:0] icmp_ln44_reg_1159_pp0_iter12_reg;
wire   [4:0] select_ln39_fu_279_p3;
reg   [4:0] select_ln39_reg_1164;
reg   [4:0] select_ln39_reg_1164_pp0_iter1_reg;
reg   [4:0] select_ln39_reg_1164_pp0_iter2_reg;
reg   [4:0] select_ln39_reg_1164_pp0_iter3_reg;
wire   [9:0] select_ln39_2_fu_293_p3;
reg   [9:0] select_ln39_2_reg_1170;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter1_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter2_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter3_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter4_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter5_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter6_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter7_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter8_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter9_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter10_reg;
reg   [9:0] select_ln39_2_reg_1170_pp0_iter11_reg;
wire   [0:0] icmp_ln44_1_fu_311_p2;
reg   [0:0] icmp_ln44_1_reg_1180;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter1_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter2_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter3_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter4_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter5_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter6_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter7_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter8_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter9_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter10_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter11_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter12_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter13_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter14_reg;
reg   [0:0] icmp_ln44_1_reg_1180_pp0_iter15_reg;
reg   [31:0] w_reg_1194;
wire   [31:0] xnor_res_fu_349_p2;
reg   [31:0] xnor_res_reg_1204;
reg   [31:0] xnor_res_reg_1204_pp0_iter6_reg;
reg   [31:0] xnor_res_reg_1204_pp0_iter7_reg;
reg   [31:0] xnor_res_reg_1204_pp0_iter8_reg;
reg   [31:0] xnor_res_reg_1204_pp0_iter9_reg;
reg   [31:0] xnor_res_reg_1204_pp0_iter10_reg;
reg   [31:0] xnor_res_reg_1204_pp0_iter11_reg;
reg   [31:0] xnor_res_reg_1204_pp0_iter12_reg;
wire   [2:0] select_ln16_4_fu_448_p3;
reg   [2:0] select_ln16_4_reg_1209;
reg   [0:0] tmp_4_reg_1214;
wire   [2:0] add_ln16_3_fu_464_p2;
reg   [2:0] add_ln16_3_reg_1219;
reg   [0:0] tmp_5_reg_1224;
reg   [0:0] tmp_6_reg_1229;
reg   [0:0] tmp_7_reg_1234;
reg   [0:0] tmp_8_reg_1239;
reg   [0:0] tmp_8_reg_1239_pp0_iter6_reg;
reg   [0:0] tmp_9_reg_1244;
reg   [0:0] tmp_9_reg_1244_pp0_iter6_reg;
reg   [0:0] tmp_10_reg_1249;
reg   [0:0] tmp_10_reg_1249_pp0_iter6_reg;
reg   [0:0] tmp_11_reg_1254;
reg   [0:0] tmp_11_reg_1254_pp0_iter6_reg;
reg   [0:0] tmp_12_reg_1259;
reg   [0:0] tmp_12_reg_1259_pp0_iter6_reg;
reg   [0:0] tmp_12_reg_1259_pp0_iter7_reg;
reg   [0:0] tmp_13_reg_1264;
reg   [0:0] tmp_13_reg_1264_pp0_iter6_reg;
reg   [0:0] tmp_13_reg_1264_pp0_iter7_reg;
reg   [0:0] tmp_14_reg_1269;
reg   [0:0] tmp_14_reg_1269_pp0_iter6_reg;
reg   [0:0] tmp_14_reg_1269_pp0_iter7_reg;
reg   [0:0] tmp_15_reg_1274;
reg   [0:0] tmp_15_reg_1274_pp0_iter6_reg;
reg   [0:0] tmp_15_reg_1274_pp0_iter7_reg;
reg   [0:0] tmp_15_reg_1274_pp0_iter8_reg;
reg   [0:0] tmp_16_reg_1279;
reg   [0:0] tmp_16_reg_1279_pp0_iter6_reg;
reg   [0:0] tmp_16_reg_1279_pp0_iter7_reg;
reg   [0:0] tmp_16_reg_1279_pp0_iter8_reg;
reg   [0:0] tmp_17_reg_1284;
reg   [0:0] tmp_17_reg_1284_pp0_iter6_reg;
reg   [0:0] tmp_17_reg_1284_pp0_iter7_reg;
reg   [0:0] tmp_17_reg_1284_pp0_iter8_reg;
reg   [0:0] tmp_18_reg_1289;
reg   [0:0] tmp_18_reg_1289_pp0_iter6_reg;
reg   [0:0] tmp_18_reg_1289_pp0_iter7_reg;
reg   [0:0] tmp_18_reg_1289_pp0_iter8_reg;
reg   [0:0] tmp_19_reg_1294;
reg   [0:0] tmp_19_reg_1294_pp0_iter6_reg;
reg   [0:0] tmp_19_reg_1294_pp0_iter7_reg;
reg   [0:0] tmp_19_reg_1294_pp0_iter8_reg;
reg   [0:0] tmp_19_reg_1294_pp0_iter9_reg;
reg   [0:0] tmp_20_reg_1299;
reg   [0:0] tmp_20_reg_1299_pp0_iter6_reg;
reg   [0:0] tmp_20_reg_1299_pp0_iter7_reg;
reg   [0:0] tmp_20_reg_1299_pp0_iter8_reg;
reg   [0:0] tmp_20_reg_1299_pp0_iter9_reg;
reg   [0:0] tmp_21_reg_1304;
reg   [0:0] tmp_21_reg_1304_pp0_iter6_reg;
reg   [0:0] tmp_21_reg_1304_pp0_iter7_reg;
reg   [0:0] tmp_21_reg_1304_pp0_iter8_reg;
reg   [0:0] tmp_21_reg_1304_pp0_iter9_reg;
reg   [0:0] tmp_22_reg_1309;
reg   [0:0] tmp_22_reg_1309_pp0_iter6_reg;
reg   [0:0] tmp_22_reg_1309_pp0_iter7_reg;
reg   [0:0] tmp_22_reg_1309_pp0_iter8_reg;
reg   [0:0] tmp_22_reg_1309_pp0_iter9_reg;
reg   [0:0] tmp_22_reg_1309_pp0_iter10_reg;
reg   [0:0] tmp_23_reg_1314;
reg   [0:0] tmp_23_reg_1314_pp0_iter6_reg;
reg   [0:0] tmp_23_reg_1314_pp0_iter7_reg;
reg   [0:0] tmp_23_reg_1314_pp0_iter8_reg;
reg   [0:0] tmp_23_reg_1314_pp0_iter9_reg;
reg   [0:0] tmp_23_reg_1314_pp0_iter10_reg;
reg   [0:0] tmp_24_reg_1319;
reg   [0:0] tmp_24_reg_1319_pp0_iter6_reg;
reg   [0:0] tmp_24_reg_1319_pp0_iter7_reg;
reg   [0:0] tmp_24_reg_1319_pp0_iter8_reg;
reg   [0:0] tmp_24_reg_1319_pp0_iter9_reg;
reg   [0:0] tmp_24_reg_1319_pp0_iter10_reg;
reg   [0:0] tmp_25_reg_1324;
reg   [0:0] tmp_25_reg_1324_pp0_iter6_reg;
reg   [0:0] tmp_25_reg_1324_pp0_iter7_reg;
reg   [0:0] tmp_25_reg_1324_pp0_iter8_reg;
reg   [0:0] tmp_25_reg_1324_pp0_iter9_reg;
reg   [0:0] tmp_25_reg_1324_pp0_iter10_reg;
reg   [0:0] tmp_26_reg_1329;
reg   [0:0] tmp_26_reg_1329_pp0_iter6_reg;
reg   [0:0] tmp_26_reg_1329_pp0_iter7_reg;
reg   [0:0] tmp_26_reg_1329_pp0_iter8_reg;
reg   [0:0] tmp_26_reg_1329_pp0_iter9_reg;
reg   [0:0] tmp_26_reg_1329_pp0_iter10_reg;
reg   [0:0] tmp_26_reg_1329_pp0_iter11_reg;
reg   [0:0] tmp_27_reg_1334;
reg   [0:0] tmp_27_reg_1334_pp0_iter6_reg;
reg   [0:0] tmp_27_reg_1334_pp0_iter7_reg;
reg   [0:0] tmp_27_reg_1334_pp0_iter8_reg;
reg   [0:0] tmp_27_reg_1334_pp0_iter9_reg;
reg   [0:0] tmp_27_reg_1334_pp0_iter10_reg;
reg   [0:0] tmp_27_reg_1334_pp0_iter11_reg;
reg   [0:0] tmp_28_reg_1339;
reg   [0:0] tmp_28_reg_1339_pp0_iter6_reg;
reg   [0:0] tmp_28_reg_1339_pp0_iter7_reg;
reg   [0:0] tmp_28_reg_1339_pp0_iter8_reg;
reg   [0:0] tmp_28_reg_1339_pp0_iter9_reg;
reg   [0:0] tmp_28_reg_1339_pp0_iter10_reg;
reg   [0:0] tmp_28_reg_1339_pp0_iter11_reg;
reg   [0:0] tmp_29_reg_1344;
reg   [0:0] tmp_29_reg_1344_pp0_iter6_reg;
reg   [0:0] tmp_29_reg_1344_pp0_iter7_reg;
reg   [0:0] tmp_29_reg_1344_pp0_iter8_reg;
reg   [0:0] tmp_29_reg_1344_pp0_iter9_reg;
reg   [0:0] tmp_29_reg_1344_pp0_iter10_reg;
reg   [0:0] tmp_29_reg_1344_pp0_iter11_reg;
reg   [0:0] tmp_29_reg_1344_pp0_iter12_reg;
wire   [3:0] select_ln16_8_fu_711_p3;
reg   [3:0] select_ln16_8_reg_1349;
wire   [3:0] add_ln16_7_fu_718_p2;
reg   [3:0] add_ln16_7_reg_1354;
wire   [3:0] select_ln16_12_fu_761_p3;
reg   [3:0] select_ln16_12_reg_1359;
wire   [4:0] select_ln16_15_fu_802_p3;
reg   [4:0] select_ln16_15_reg_1365;
wire   [4:0] add_ln16_14_fu_809_p2;
reg   [4:0] add_ln16_14_reg_1370;
wire   [4:0] select_ln16_19_fu_852_p3;
reg   [4:0] select_ln16_19_reg_1375;
wire   [4:0] select_ln16_22_fu_889_p3;
reg   [4:0] select_ln16_22_reg_1381;
wire   [4:0] add_ln16_21_fu_896_p2;
reg   [4:0] add_ln16_21_reg_1386;
wire   [4:0] select_ln16_26_fu_939_p3;
reg   [4:0] select_ln16_26_reg_1391;
wire   [4:0] select_ln16_29_fu_982_p3;
reg   [4:0] select_ln16_29_reg_1397;
reg   [9:0] hidden_out_addr_reg_1413;
reg   [9:0] hidden_out_addr_reg_1413_pp0_iter13_reg;
reg   [9:0] hidden_out_addr_reg_1413_pp0_iter14_reg;
reg   [9:0] hidden_out_addr_reg_1413_pp0_iter15_reg;
reg   [12:0] bn_offset_load_reg_1428;
reg  signed [12:0] bn_offset_load_reg_1428_pp0_iter14_reg;
wire   [63:0] zext_ln46_fu_335_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln44_1_fu_339_p1;
wire   [63:0] zext_ln39_fu_946_p1;
reg   [9:0] popcount_acc_fu_152;
wire   [9:0] popcount_acc_1_fu_1039_p2;
wire    ap_loop_init;
reg   [4:0] j_fu_156;
wire   [4:0] add_ln44_fu_305_p2;
reg   [4:0] ap_sig_allocacmp_j_load;
reg   [9:0] i_fu_160;
reg   [9:0] ap_sig_allocacmp_i_load;
reg   [13:0] indvar_flatten_fu_164;
wire   [13:0] add_ln39_fu_261_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten_load;
reg    weights_l1_ce0_local;
reg    input_img_ce0_local;
reg    bn_scale_ce0_local;
reg    bn_offset_ce0_local;
reg    hidden_out_we0_local;
wire   [6:0] select_ln66_fu_1099_p3;
reg    hidden_out_ce0_local;
wire   [9:0] add_ln39_1_fu_287_p2;
wire   [13:0] grp_fu_1108_p3;
wire   [31:0] xor_ln49_fu_343_p2;
wire   [0:0] trunc_ln16_fu_354_p1;
wire   [0:0] tmp_fu_358_p3;
wire   [1:0] select_ln16_fu_366_p3;
wire   [1:0] zext_ln16_fu_374_p1;
wire   [1:0] select_ln16_1_fu_378_p3;
wire   [0:0] tmp_1_fu_386_p3;
wire   [1:0] add_ln16_fu_394_p2;
wire   [1:0] select_ln16_2_fu_400_p3;
wire   [2:0] zext_ln16_1_fu_408_p1;
wire   [0:0] tmp_2_fu_412_p3;
wire   [2:0] add_ln16_1_fu_420_p2;
wire   [2:0] select_ln16_3_fu_426_p3;
wire   [0:0] tmp_3_fu_434_p3;
wire   [2:0] add_ln16_2_fu_442_p2;
wire   [2:0] select_ln16_5_fu_670_p3;
wire   [2:0] add_ln16_4_fu_675_p2;
wire   [2:0] select_ln16_6_fu_681_p3;
wire   [3:0] zext_ln16_2_fu_688_p1;
wire   [3:0] add_ln16_5_fu_692_p2;
wire   [3:0] select_ln16_7_fu_698_p3;
wire   [3:0] add_ln16_6_fu_705_p2;
wire   [3:0] select_ln16_9_fu_724_p3;
wire   [3:0] add_ln16_8_fu_729_p2;
wire   [3:0] select_ln16_10_fu_735_p3;
wire   [3:0] add_ln16_9_fu_742_p2;
wire   [3:0] select_ln16_11_fu_748_p3;
wire   [3:0] add_ln16_10_fu_755_p2;
wire   [3:0] add_ln16_11_fu_768_p2;
wire   [3:0] select_ln16_13_fu_773_p3;
wire   [3:0] add_ln16_12_fu_779_p2;
wire   [3:0] select_ln16_14_fu_785_p3;
wire   [4:0] zext_ln16_3_fu_792_p1;
wire   [4:0] add_ln16_13_fu_796_p2;
wire   [4:0] select_ln16_16_fu_815_p3;
wire   [4:0] add_ln16_15_fu_820_p2;
wire   [4:0] select_ln16_17_fu_826_p3;
wire   [4:0] add_ln16_16_fu_833_p2;
wire   [4:0] select_ln16_18_fu_839_p3;
wire   [4:0] add_ln16_17_fu_846_p2;
wire   [4:0] add_ln16_18_fu_859_p2;
wire   [4:0] select_ln16_20_fu_864_p3;
wire   [4:0] add_ln16_19_fu_870_p2;
wire   [4:0] select_ln16_21_fu_876_p3;
wire   [4:0] add_ln16_20_fu_883_p2;
wire   [4:0] select_ln16_23_fu_902_p3;
wire   [4:0] add_ln16_22_fu_907_p2;
wire   [4:0] select_ln16_24_fu_913_p3;
wire   [4:0] add_ln16_23_fu_920_p2;
wire   [4:0] select_ln16_25_fu_926_p3;
wire   [4:0] add_ln16_24_fu_933_p2;
wire   [4:0] add_ln16_25_fu_952_p2;
wire   [4:0] select_ln16_27_fu_957_p3;
wire   [4:0] add_ln16_26_fu_963_p2;
wire   [4:0] select_ln16_28_fu_969_p3;
wire   [4:0] add_ln16_27_fu_976_p2;
wire   [4:0] add_ln16_28_fu_999_p2;
wire   [4:0] select_ln16_30_fu_1004_p3;
wire   [5:0] zext_ln16_4_fu_1010_p1;
wire   [0:0] tmp_30_fu_1014_p3;
wire   [5:0] add_ln16_29_fu_1021_p2;
wire   [5:0] select_ln16_31_fu_1027_p3;
wire   [9:0] zext_ln52_fu_1035_p1;
wire   [9:0] select_ln39_1_fu_992_p3;
wire   [10:0] shl_ln_fu_1045_p3;
wire  signed [10:0] bipolar_val_fu_1053_p2;
wire  signed [15:0] grp_fu_1117_p3;
wire   [7:0] trunc_ln_fu_1075_p4;
wire   [0:0] icmp_ln66_fu_1093_p2;
wire   [6:0] trunc_ln_cast_fu_1084_p4;
wire   [9:0] grp_fu_1108_p0;
wire   [4:0] grp_fu_1108_p1;
wire   [4:0] grp_fu_1108_p2;
wire   [4:0] grp_fu_1117_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [13:0] grp_fu_1108_p00;
wire   [13:0] grp_fu_1108_p20;
wire   [15:0] grp_fu_1117_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 popcount_acc_fu_152 = 10'd0;
#0 j_fu_156 = 5'd0;
#0 i_fu_160 = 10'd0;
#0 indvar_flatten_fu_164 = 14'd0;
#0 ap_done_reg = 1'b0;
end

bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_44_1_weights_l1_ROM_1P_BRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 16000 ),
    .AddressWidth( 14 ))
weights_l1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights_l1_address0),
    .ce0(weights_l1_ce0_local),
    .q0(weights_l1_q0)
);

bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_44_1_bn_scale_ROM_1P_BRAM_1R #(
    .DataWidth( 5 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
bn_scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bn_scale_address0),
    .ce0(bn_scale_ce0_local),
    .q0(bn_scale_q0)
);

bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_44_1_bn_offset_ROM_1P_BRAM_1R #(
    .DataWidth( 13 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
bn_offset_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bn_offset_address0),
    .ce0(bn_offset_ce0_local),
    .q0(bn_offset_q0)
);

bgn_inference_mac_muladd_10ns_5ns_5ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 14 ))
mac_muladd_10ns_5ns_5ns_14_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1108_p0),
    .din1(grp_fu_1108_p1),
    .din2(grp_fu_1108_p2),
    .ce(1'b1),
    .dout(grp_fu_1108_p3)
);

bgn_inference_mac_muladd_11s_5ns_13s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mac_muladd_11s_5ns_13s_16_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bipolar_val_fu_1053_p2),
    .din1(grp_fu_1117_p1),
    .din2(bn_offset_load_reg_1428_pp0_iter14_reg),
    .ce(1'b1),
    .dout(grp_fu_1117_p3)
);

bgn_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_255_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_160 <= select_ln39_2_fu_293_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_160 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_255_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_164 <= add_ln39_fu_261_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_164 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_255_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_156 <= add_ln44_fu_305_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_156 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            popcount_acc_fu_152 <= 10'd0;
        end else if ((ap_enable_reg_pp0_iter13 == 1'b1)) begin
            popcount_acc_fu_152 <= popcount_acc_1_fu_1039_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln16_14_reg_1370 <= add_ln16_14_fu_809_p2;
        add_ln16_21_reg_1386 <= add_ln16_21_fu_896_p2;
        add_ln16_3_reg_1219 <= add_ln16_3_fu_464_p2;
        add_ln16_7_reg_1354 <= add_ln16_7_fu_718_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        bn_offset_load_reg_1428 <= bn_offset_q0;
        bn_offset_load_reg_1428_pp0_iter14_reg <= bn_offset_load_reg_1428;
        hidden_out_addr_reg_1413 <= zext_ln39_fu_946_p1;
        hidden_out_addr_reg_1413_pp0_iter13_reg <= hidden_out_addr_reg_1413;
        hidden_out_addr_reg_1413_pp0_iter14_reg <= hidden_out_addr_reg_1413_pp0_iter13_reg;
        hidden_out_addr_reg_1413_pp0_iter15_reg <= hidden_out_addr_reg_1413_pp0_iter14_reg;
        icmp_ln44_1_reg_1180_pp0_iter10_reg <= icmp_ln44_1_reg_1180_pp0_iter9_reg;
        icmp_ln44_1_reg_1180_pp0_iter11_reg <= icmp_ln44_1_reg_1180_pp0_iter10_reg;
        icmp_ln44_1_reg_1180_pp0_iter12_reg <= icmp_ln44_1_reg_1180_pp0_iter11_reg;
        icmp_ln44_1_reg_1180_pp0_iter13_reg <= icmp_ln44_1_reg_1180_pp0_iter12_reg;
        icmp_ln44_1_reg_1180_pp0_iter14_reg <= icmp_ln44_1_reg_1180_pp0_iter13_reg;
        icmp_ln44_1_reg_1180_pp0_iter15_reg <= icmp_ln44_1_reg_1180_pp0_iter14_reg;
        icmp_ln44_1_reg_1180_pp0_iter2_reg <= icmp_ln44_1_reg_1180_pp0_iter1_reg;
        icmp_ln44_1_reg_1180_pp0_iter3_reg <= icmp_ln44_1_reg_1180_pp0_iter2_reg;
        icmp_ln44_1_reg_1180_pp0_iter4_reg <= icmp_ln44_1_reg_1180_pp0_iter3_reg;
        icmp_ln44_1_reg_1180_pp0_iter5_reg <= icmp_ln44_1_reg_1180_pp0_iter4_reg;
        icmp_ln44_1_reg_1180_pp0_iter6_reg <= icmp_ln44_1_reg_1180_pp0_iter5_reg;
        icmp_ln44_1_reg_1180_pp0_iter7_reg <= icmp_ln44_1_reg_1180_pp0_iter6_reg;
        icmp_ln44_1_reg_1180_pp0_iter8_reg <= icmp_ln44_1_reg_1180_pp0_iter7_reg;
        icmp_ln44_1_reg_1180_pp0_iter9_reg <= icmp_ln44_1_reg_1180_pp0_iter8_reg;
        icmp_ln44_reg_1159_pp0_iter10_reg <= icmp_ln44_reg_1159_pp0_iter9_reg;
        icmp_ln44_reg_1159_pp0_iter11_reg <= icmp_ln44_reg_1159_pp0_iter10_reg;
        icmp_ln44_reg_1159_pp0_iter12_reg <= icmp_ln44_reg_1159_pp0_iter11_reg;
        icmp_ln44_reg_1159_pp0_iter2_reg <= icmp_ln44_reg_1159_pp0_iter1_reg;
        icmp_ln44_reg_1159_pp0_iter3_reg <= icmp_ln44_reg_1159_pp0_iter2_reg;
        icmp_ln44_reg_1159_pp0_iter4_reg <= icmp_ln44_reg_1159_pp0_iter3_reg;
        icmp_ln44_reg_1159_pp0_iter5_reg <= icmp_ln44_reg_1159_pp0_iter4_reg;
        icmp_ln44_reg_1159_pp0_iter6_reg <= icmp_ln44_reg_1159_pp0_iter5_reg;
        icmp_ln44_reg_1159_pp0_iter7_reg <= icmp_ln44_reg_1159_pp0_iter6_reg;
        icmp_ln44_reg_1159_pp0_iter8_reg <= icmp_ln44_reg_1159_pp0_iter7_reg;
        icmp_ln44_reg_1159_pp0_iter9_reg <= icmp_ln44_reg_1159_pp0_iter8_reg;
        select_ln16_12_reg_1359 <= select_ln16_12_fu_761_p3;
        select_ln16_15_reg_1365 <= select_ln16_15_fu_802_p3;
        select_ln16_19_reg_1375 <= select_ln16_19_fu_852_p3;
        select_ln16_22_reg_1381 <= select_ln16_22_fu_889_p3;
        select_ln16_26_reg_1391 <= select_ln16_26_fu_939_p3;
        select_ln16_29_reg_1397 <= select_ln16_29_fu_982_p3;
        select_ln16_4_reg_1209 <= select_ln16_4_fu_448_p3;
        select_ln16_8_reg_1349 <= select_ln16_8_fu_711_p3;
        select_ln39_2_reg_1170_pp0_iter10_reg <= select_ln39_2_reg_1170_pp0_iter9_reg;
        select_ln39_2_reg_1170_pp0_iter11_reg <= select_ln39_2_reg_1170_pp0_iter10_reg;
        select_ln39_2_reg_1170_pp0_iter2_reg <= select_ln39_2_reg_1170_pp0_iter1_reg;
        select_ln39_2_reg_1170_pp0_iter3_reg <= select_ln39_2_reg_1170_pp0_iter2_reg;
        select_ln39_2_reg_1170_pp0_iter4_reg <= select_ln39_2_reg_1170_pp0_iter3_reg;
        select_ln39_2_reg_1170_pp0_iter5_reg <= select_ln39_2_reg_1170_pp0_iter4_reg;
        select_ln39_2_reg_1170_pp0_iter6_reg <= select_ln39_2_reg_1170_pp0_iter5_reg;
        select_ln39_2_reg_1170_pp0_iter7_reg <= select_ln39_2_reg_1170_pp0_iter6_reg;
        select_ln39_2_reg_1170_pp0_iter8_reg <= select_ln39_2_reg_1170_pp0_iter7_reg;
        select_ln39_2_reg_1170_pp0_iter9_reg <= select_ln39_2_reg_1170_pp0_iter8_reg;
        select_ln39_reg_1164_pp0_iter2_reg <= select_ln39_reg_1164_pp0_iter1_reg;
        select_ln39_reg_1164_pp0_iter3_reg <= select_ln39_reg_1164_pp0_iter2_reg;
        tmp_10_reg_1249 <= xnor_res_fu_349_p2[32'd11];
        tmp_10_reg_1249_pp0_iter6_reg <= tmp_10_reg_1249;
        tmp_11_reg_1254 <= xnor_res_fu_349_p2[32'd12];
        tmp_11_reg_1254_pp0_iter6_reg <= tmp_11_reg_1254;
        tmp_12_reg_1259 <= xnor_res_fu_349_p2[32'd13];
        tmp_12_reg_1259_pp0_iter6_reg <= tmp_12_reg_1259;
        tmp_12_reg_1259_pp0_iter7_reg <= tmp_12_reg_1259_pp0_iter6_reg;
        tmp_13_reg_1264 <= xnor_res_fu_349_p2[32'd14];
        tmp_13_reg_1264_pp0_iter6_reg <= tmp_13_reg_1264;
        tmp_13_reg_1264_pp0_iter7_reg <= tmp_13_reg_1264_pp0_iter6_reg;
        tmp_14_reg_1269 <= xnor_res_fu_349_p2[32'd15];
        tmp_14_reg_1269_pp0_iter6_reg <= tmp_14_reg_1269;
        tmp_14_reg_1269_pp0_iter7_reg <= tmp_14_reg_1269_pp0_iter6_reg;
        tmp_15_reg_1274 <= xnor_res_fu_349_p2[32'd16];
        tmp_15_reg_1274_pp0_iter6_reg <= tmp_15_reg_1274;
        tmp_15_reg_1274_pp0_iter7_reg <= tmp_15_reg_1274_pp0_iter6_reg;
        tmp_15_reg_1274_pp0_iter8_reg <= tmp_15_reg_1274_pp0_iter7_reg;
        tmp_16_reg_1279 <= xnor_res_fu_349_p2[32'd17];
        tmp_16_reg_1279_pp0_iter6_reg <= tmp_16_reg_1279;
        tmp_16_reg_1279_pp0_iter7_reg <= tmp_16_reg_1279_pp0_iter6_reg;
        tmp_16_reg_1279_pp0_iter8_reg <= tmp_16_reg_1279_pp0_iter7_reg;
        tmp_17_reg_1284 <= xnor_res_fu_349_p2[32'd18];
        tmp_17_reg_1284_pp0_iter6_reg <= tmp_17_reg_1284;
        tmp_17_reg_1284_pp0_iter7_reg <= tmp_17_reg_1284_pp0_iter6_reg;
        tmp_17_reg_1284_pp0_iter8_reg <= tmp_17_reg_1284_pp0_iter7_reg;
        tmp_18_reg_1289 <= xnor_res_fu_349_p2[32'd19];
        tmp_18_reg_1289_pp0_iter6_reg <= tmp_18_reg_1289;
        tmp_18_reg_1289_pp0_iter7_reg <= tmp_18_reg_1289_pp0_iter6_reg;
        tmp_18_reg_1289_pp0_iter8_reg <= tmp_18_reg_1289_pp0_iter7_reg;
        tmp_19_reg_1294 <= xnor_res_fu_349_p2[32'd20];
        tmp_19_reg_1294_pp0_iter6_reg <= tmp_19_reg_1294;
        tmp_19_reg_1294_pp0_iter7_reg <= tmp_19_reg_1294_pp0_iter6_reg;
        tmp_19_reg_1294_pp0_iter8_reg <= tmp_19_reg_1294_pp0_iter7_reg;
        tmp_19_reg_1294_pp0_iter9_reg <= tmp_19_reg_1294_pp0_iter8_reg;
        tmp_20_reg_1299 <= xnor_res_fu_349_p2[32'd21];
        tmp_20_reg_1299_pp0_iter6_reg <= tmp_20_reg_1299;
        tmp_20_reg_1299_pp0_iter7_reg <= tmp_20_reg_1299_pp0_iter6_reg;
        tmp_20_reg_1299_pp0_iter8_reg <= tmp_20_reg_1299_pp0_iter7_reg;
        tmp_20_reg_1299_pp0_iter9_reg <= tmp_20_reg_1299_pp0_iter8_reg;
        tmp_21_reg_1304 <= xnor_res_fu_349_p2[32'd22];
        tmp_21_reg_1304_pp0_iter6_reg <= tmp_21_reg_1304;
        tmp_21_reg_1304_pp0_iter7_reg <= tmp_21_reg_1304_pp0_iter6_reg;
        tmp_21_reg_1304_pp0_iter8_reg <= tmp_21_reg_1304_pp0_iter7_reg;
        tmp_21_reg_1304_pp0_iter9_reg <= tmp_21_reg_1304_pp0_iter8_reg;
        tmp_22_reg_1309 <= xnor_res_fu_349_p2[32'd23];
        tmp_22_reg_1309_pp0_iter10_reg <= tmp_22_reg_1309_pp0_iter9_reg;
        tmp_22_reg_1309_pp0_iter6_reg <= tmp_22_reg_1309;
        tmp_22_reg_1309_pp0_iter7_reg <= tmp_22_reg_1309_pp0_iter6_reg;
        tmp_22_reg_1309_pp0_iter8_reg <= tmp_22_reg_1309_pp0_iter7_reg;
        tmp_22_reg_1309_pp0_iter9_reg <= tmp_22_reg_1309_pp0_iter8_reg;
        tmp_23_reg_1314 <= xnor_res_fu_349_p2[32'd24];
        tmp_23_reg_1314_pp0_iter10_reg <= tmp_23_reg_1314_pp0_iter9_reg;
        tmp_23_reg_1314_pp0_iter6_reg <= tmp_23_reg_1314;
        tmp_23_reg_1314_pp0_iter7_reg <= tmp_23_reg_1314_pp0_iter6_reg;
        tmp_23_reg_1314_pp0_iter8_reg <= tmp_23_reg_1314_pp0_iter7_reg;
        tmp_23_reg_1314_pp0_iter9_reg <= tmp_23_reg_1314_pp0_iter8_reg;
        tmp_24_reg_1319 <= xnor_res_fu_349_p2[32'd25];
        tmp_24_reg_1319_pp0_iter10_reg <= tmp_24_reg_1319_pp0_iter9_reg;
        tmp_24_reg_1319_pp0_iter6_reg <= tmp_24_reg_1319;
        tmp_24_reg_1319_pp0_iter7_reg <= tmp_24_reg_1319_pp0_iter6_reg;
        tmp_24_reg_1319_pp0_iter8_reg <= tmp_24_reg_1319_pp0_iter7_reg;
        tmp_24_reg_1319_pp0_iter9_reg <= tmp_24_reg_1319_pp0_iter8_reg;
        tmp_25_reg_1324 <= xnor_res_fu_349_p2[32'd26];
        tmp_25_reg_1324_pp0_iter10_reg <= tmp_25_reg_1324_pp0_iter9_reg;
        tmp_25_reg_1324_pp0_iter6_reg <= tmp_25_reg_1324;
        tmp_25_reg_1324_pp0_iter7_reg <= tmp_25_reg_1324_pp0_iter6_reg;
        tmp_25_reg_1324_pp0_iter8_reg <= tmp_25_reg_1324_pp0_iter7_reg;
        tmp_25_reg_1324_pp0_iter9_reg <= tmp_25_reg_1324_pp0_iter8_reg;
        tmp_26_reg_1329 <= xnor_res_fu_349_p2[32'd27];
        tmp_26_reg_1329_pp0_iter10_reg <= tmp_26_reg_1329_pp0_iter9_reg;
        tmp_26_reg_1329_pp0_iter11_reg <= tmp_26_reg_1329_pp0_iter10_reg;
        tmp_26_reg_1329_pp0_iter6_reg <= tmp_26_reg_1329;
        tmp_26_reg_1329_pp0_iter7_reg <= tmp_26_reg_1329_pp0_iter6_reg;
        tmp_26_reg_1329_pp0_iter8_reg <= tmp_26_reg_1329_pp0_iter7_reg;
        tmp_26_reg_1329_pp0_iter9_reg <= tmp_26_reg_1329_pp0_iter8_reg;
        tmp_27_reg_1334 <= xnor_res_fu_349_p2[32'd28];
        tmp_27_reg_1334_pp0_iter10_reg <= tmp_27_reg_1334_pp0_iter9_reg;
        tmp_27_reg_1334_pp0_iter11_reg <= tmp_27_reg_1334_pp0_iter10_reg;
        tmp_27_reg_1334_pp0_iter6_reg <= tmp_27_reg_1334;
        tmp_27_reg_1334_pp0_iter7_reg <= tmp_27_reg_1334_pp0_iter6_reg;
        tmp_27_reg_1334_pp0_iter8_reg <= tmp_27_reg_1334_pp0_iter7_reg;
        tmp_27_reg_1334_pp0_iter9_reg <= tmp_27_reg_1334_pp0_iter8_reg;
        tmp_28_reg_1339 <= xnor_res_fu_349_p2[32'd29];
        tmp_28_reg_1339_pp0_iter10_reg <= tmp_28_reg_1339_pp0_iter9_reg;
        tmp_28_reg_1339_pp0_iter11_reg <= tmp_28_reg_1339_pp0_iter10_reg;
        tmp_28_reg_1339_pp0_iter6_reg <= tmp_28_reg_1339;
        tmp_28_reg_1339_pp0_iter7_reg <= tmp_28_reg_1339_pp0_iter6_reg;
        tmp_28_reg_1339_pp0_iter8_reg <= tmp_28_reg_1339_pp0_iter7_reg;
        tmp_28_reg_1339_pp0_iter9_reg <= tmp_28_reg_1339_pp0_iter8_reg;
        tmp_29_reg_1344 <= xnor_res_fu_349_p2[32'd30];
        tmp_29_reg_1344_pp0_iter10_reg <= tmp_29_reg_1344_pp0_iter9_reg;
        tmp_29_reg_1344_pp0_iter11_reg <= tmp_29_reg_1344_pp0_iter10_reg;
        tmp_29_reg_1344_pp0_iter12_reg <= tmp_29_reg_1344_pp0_iter11_reg;
        tmp_29_reg_1344_pp0_iter6_reg <= tmp_29_reg_1344;
        tmp_29_reg_1344_pp0_iter7_reg <= tmp_29_reg_1344_pp0_iter6_reg;
        tmp_29_reg_1344_pp0_iter8_reg <= tmp_29_reg_1344_pp0_iter7_reg;
        tmp_29_reg_1344_pp0_iter9_reg <= tmp_29_reg_1344_pp0_iter8_reg;
        tmp_4_reg_1214 <= xnor_res_fu_349_p2[32'd5];
        tmp_5_reg_1224 <= xnor_res_fu_349_p2[32'd6];
        tmp_6_reg_1229 <= xnor_res_fu_349_p2[32'd7];
        tmp_7_reg_1234 <= xnor_res_fu_349_p2[32'd8];
        tmp_8_reg_1239 <= xnor_res_fu_349_p2[32'd9];
        tmp_8_reg_1239_pp0_iter6_reg <= tmp_8_reg_1239;
        tmp_9_reg_1244 <= xnor_res_fu_349_p2[32'd10];
        tmp_9_reg_1244_pp0_iter6_reg <= tmp_9_reg_1244;
        w_reg_1194 <= weights_l1_q0;
        xnor_res_reg_1204 <= xnor_res_fu_349_p2;
        xnor_res_reg_1204_pp0_iter10_reg <= xnor_res_reg_1204_pp0_iter9_reg;
        xnor_res_reg_1204_pp0_iter11_reg <= xnor_res_reg_1204_pp0_iter10_reg;
        xnor_res_reg_1204_pp0_iter12_reg <= xnor_res_reg_1204_pp0_iter11_reg;
        xnor_res_reg_1204_pp0_iter6_reg <= xnor_res_reg_1204;
        xnor_res_reg_1204_pp0_iter7_reg <= xnor_res_reg_1204_pp0_iter6_reg;
        xnor_res_reg_1204_pp0_iter8_reg <= xnor_res_reg_1204_pp0_iter7_reg;
        xnor_res_reg_1204_pp0_iter9_reg <= xnor_res_reg_1204_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln44_1_reg_1180 <= icmp_ln44_1_fu_311_p2;
        icmp_ln44_1_reg_1180_pp0_iter1_reg <= icmp_ln44_1_reg_1180;
        icmp_ln44_reg_1159 <= icmp_ln44_fu_273_p2;
        icmp_ln44_reg_1159_pp0_iter1_reg <= icmp_ln44_reg_1159;
        select_ln39_2_reg_1170 <= select_ln39_2_fu_293_p3;
        select_ln39_2_reg_1170_pp0_iter1_reg <= select_ln39_2_reg_1170;
        select_ln39_reg_1164 <= select_ln39_fu_279_p3;
        select_ln39_reg_1164_pp0_iter1_reg <= select_ln39_reg_1164;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_255_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 10'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_160;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_164;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 5'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_156;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        bn_offset_ce0_local = 1'b1;
    end else begin
        bn_offset_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        bn_scale_ce0_local = 1'b1;
    end else begin
        bn_scale_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1))) begin
        hidden_out_ce0_local = 1'b1;
    end else begin
        hidden_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln44_1_reg_1180_pp0_iter15_reg == 1'd1))) begin
        hidden_out_we0_local = 1'b1;
    end else begin
        hidden_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        input_img_ce0_local = 1'b1;
    end else begin
        input_img_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        weights_l1_ce0_local = 1'b1;
    end else begin
        weights_l1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_10_fu_755_p2 = (select_ln16_11_fu_748_p3 + 4'd1);

assign add_ln16_11_fu_768_p2 = (select_ln16_12_reg_1359 + 4'd1);

assign add_ln16_12_fu_779_p2 = (select_ln16_13_fu_773_p3 + 4'd1);

assign add_ln16_13_fu_796_p2 = (zext_ln16_3_fu_792_p1 + 5'd1);

assign add_ln16_14_fu_809_p2 = (select_ln16_15_fu_802_p3 + 5'd1);

assign add_ln16_15_fu_820_p2 = (select_ln16_16_fu_815_p3 + 5'd1);

assign add_ln16_16_fu_833_p2 = (select_ln16_17_fu_826_p3 + 5'd1);

assign add_ln16_17_fu_846_p2 = (select_ln16_18_fu_839_p3 + 5'd1);

assign add_ln16_18_fu_859_p2 = (select_ln16_19_reg_1375 + 5'd1);

assign add_ln16_19_fu_870_p2 = (select_ln16_20_fu_864_p3 + 5'd1);

assign add_ln16_1_fu_420_p2 = (zext_ln16_1_fu_408_p1 + 3'd1);

assign add_ln16_20_fu_883_p2 = (select_ln16_21_fu_876_p3 + 5'd1);

assign add_ln16_21_fu_896_p2 = (select_ln16_22_fu_889_p3 + 5'd1);

assign add_ln16_22_fu_907_p2 = (select_ln16_23_fu_902_p3 + 5'd1);

assign add_ln16_23_fu_920_p2 = (select_ln16_24_fu_913_p3 + 5'd1);

assign add_ln16_24_fu_933_p2 = (select_ln16_25_fu_926_p3 + 5'd1);

assign add_ln16_25_fu_952_p2 = (select_ln16_26_reg_1391 + 5'd1);

assign add_ln16_26_fu_963_p2 = (select_ln16_27_fu_957_p3 + 5'd1);

assign add_ln16_27_fu_976_p2 = (select_ln16_28_fu_969_p3 + 5'd1);

assign add_ln16_28_fu_999_p2 = (select_ln16_29_reg_1397 + 5'd1);

assign add_ln16_29_fu_1021_p2 = (zext_ln16_4_fu_1010_p1 + 6'd1);

assign add_ln16_2_fu_442_p2 = (select_ln16_3_fu_426_p3 + 3'd1);

assign add_ln16_3_fu_464_p2 = (select_ln16_4_fu_448_p3 + 3'd1);

assign add_ln16_4_fu_675_p2 = (select_ln16_5_fu_670_p3 + 3'd1);

assign add_ln16_5_fu_692_p2 = (zext_ln16_2_fu_688_p1 + 4'd1);

assign add_ln16_6_fu_705_p2 = (select_ln16_7_fu_698_p3 + 4'd1);

assign add_ln16_7_fu_718_p2 = (select_ln16_8_fu_711_p3 + 4'd1);

assign add_ln16_8_fu_729_p2 = (select_ln16_9_fu_724_p3 + 4'd1);

assign add_ln16_9_fu_742_p2 = (select_ln16_10_fu_735_p3 + 4'd1);

assign add_ln16_fu_394_p2 = (select_ln16_1_fu_378_p3 + 2'd1);

assign add_ln39_1_fu_287_p2 = (ap_sig_allocacmp_i_load + 10'd1);

assign add_ln39_fu_261_p2 = (ap_sig_allocacmp_indvar_flatten_load + 14'd1);

assign add_ln44_fu_305_p2 = (select_ln39_fu_279_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bipolar_val_fu_1053_p2 = ($signed(shl_ln_fu_1045_p3) + $signed(11'd1264));

assign bn_offset_address0 = zext_ln39_fu_946_p1;

assign bn_scale_address0 = zext_ln39_fu_946_p1;

assign grp_fu_1108_p0 = grp_fu_1108_p00;

assign grp_fu_1108_p00 = select_ln39_2_fu_293_p3;

assign grp_fu_1108_p1 = 14'd25;

assign grp_fu_1108_p2 = grp_fu_1108_p20;

assign grp_fu_1108_p20 = select_ln39_reg_1164_pp0_iter1_reg;

assign grp_fu_1117_p1 = grp_fu_1117_p10;

assign grp_fu_1117_p10 = bn_scale_q0;

assign hidden_out_address0 = hidden_out_addr_reg_1413_pp0_iter15_reg;

assign hidden_out_ce0 = hidden_out_ce0_local;

assign hidden_out_d0 = select_ln66_fu_1099_p3;

assign hidden_out_we0 = hidden_out_we0_local;

assign icmp_ln39_fu_255_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 14'd16000) ? 1'b1 : 1'b0);

assign icmp_ln44_1_fu_311_p2 = ((add_ln44_fu_305_p2 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_273_p2 = ((ap_sig_allocacmp_j_load == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1093_p2 = (($signed(trunc_ln_fu_1075_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign input_img_address0 = zext_ln44_1_fu_339_p1;

assign input_img_ce0 = input_img_ce0_local;

assign popcount_acc_1_fu_1039_p2 = (zext_ln52_fu_1035_p1 + select_ln39_1_fu_992_p3);

assign select_ln16_10_fu_735_p3 = ((tmp_9_reg_1244_pp0_iter6_reg[0:0] == 1'b1) ? add_ln16_8_fu_729_p2 : select_ln16_9_fu_724_p3);

assign select_ln16_11_fu_748_p3 = ((tmp_10_reg_1249_pp0_iter6_reg[0:0] == 1'b1) ? add_ln16_9_fu_742_p2 : select_ln16_10_fu_735_p3);

assign select_ln16_12_fu_761_p3 = ((tmp_11_reg_1254_pp0_iter6_reg[0:0] == 1'b1) ? add_ln16_10_fu_755_p2 : select_ln16_11_fu_748_p3);

assign select_ln16_13_fu_773_p3 = ((tmp_12_reg_1259_pp0_iter7_reg[0:0] == 1'b1) ? add_ln16_11_fu_768_p2 : select_ln16_12_reg_1359);

assign select_ln16_14_fu_785_p3 = ((tmp_13_reg_1264_pp0_iter7_reg[0:0] == 1'b1) ? add_ln16_12_fu_779_p2 : select_ln16_13_fu_773_p3);

assign select_ln16_15_fu_802_p3 = ((tmp_14_reg_1269_pp0_iter7_reg[0:0] == 1'b1) ? add_ln16_13_fu_796_p2 : zext_ln16_3_fu_792_p1);

assign select_ln16_16_fu_815_p3 = ((tmp_15_reg_1274_pp0_iter8_reg[0:0] == 1'b1) ? add_ln16_14_reg_1370 : select_ln16_15_reg_1365);

assign select_ln16_17_fu_826_p3 = ((tmp_16_reg_1279_pp0_iter8_reg[0:0] == 1'b1) ? add_ln16_15_fu_820_p2 : select_ln16_16_fu_815_p3);

assign select_ln16_18_fu_839_p3 = ((tmp_17_reg_1284_pp0_iter8_reg[0:0] == 1'b1) ? add_ln16_16_fu_833_p2 : select_ln16_17_fu_826_p3);

assign select_ln16_19_fu_852_p3 = ((tmp_18_reg_1289_pp0_iter8_reg[0:0] == 1'b1) ? add_ln16_17_fu_846_p2 : select_ln16_18_fu_839_p3);

assign select_ln16_1_fu_378_p3 = ((tmp_fu_358_p3[0:0] == 1'b1) ? select_ln16_fu_366_p3 : zext_ln16_fu_374_p1);

assign select_ln16_20_fu_864_p3 = ((tmp_19_reg_1294_pp0_iter9_reg[0:0] == 1'b1) ? add_ln16_18_fu_859_p2 : select_ln16_19_reg_1375);

assign select_ln16_21_fu_876_p3 = ((tmp_20_reg_1299_pp0_iter9_reg[0:0] == 1'b1) ? add_ln16_19_fu_870_p2 : select_ln16_20_fu_864_p3);

assign select_ln16_22_fu_889_p3 = ((tmp_21_reg_1304_pp0_iter9_reg[0:0] == 1'b1) ? add_ln16_20_fu_883_p2 : select_ln16_21_fu_876_p3);

assign select_ln16_23_fu_902_p3 = ((tmp_22_reg_1309_pp0_iter10_reg[0:0] == 1'b1) ? add_ln16_21_reg_1386 : select_ln16_22_reg_1381);

assign select_ln16_24_fu_913_p3 = ((tmp_23_reg_1314_pp0_iter10_reg[0:0] == 1'b1) ? add_ln16_22_fu_907_p2 : select_ln16_23_fu_902_p3);

assign select_ln16_25_fu_926_p3 = ((tmp_24_reg_1319_pp0_iter10_reg[0:0] == 1'b1) ? add_ln16_23_fu_920_p2 : select_ln16_24_fu_913_p3);

assign select_ln16_26_fu_939_p3 = ((tmp_25_reg_1324_pp0_iter10_reg[0:0] == 1'b1) ? add_ln16_24_fu_933_p2 : select_ln16_25_fu_926_p3);

assign select_ln16_27_fu_957_p3 = ((tmp_26_reg_1329_pp0_iter11_reg[0:0] == 1'b1) ? add_ln16_25_fu_952_p2 : select_ln16_26_reg_1391);

assign select_ln16_28_fu_969_p3 = ((tmp_27_reg_1334_pp0_iter11_reg[0:0] == 1'b1) ? add_ln16_26_fu_963_p2 : select_ln16_27_fu_957_p3);

assign select_ln16_29_fu_982_p3 = ((tmp_28_reg_1339_pp0_iter11_reg[0:0] == 1'b1) ? add_ln16_27_fu_976_p2 : select_ln16_28_fu_969_p3);

assign select_ln16_2_fu_400_p3 = ((tmp_1_fu_386_p3[0:0] == 1'b1) ? add_ln16_fu_394_p2 : select_ln16_1_fu_378_p3);

assign select_ln16_30_fu_1004_p3 = ((tmp_29_reg_1344_pp0_iter12_reg[0:0] == 1'b1) ? add_ln16_28_fu_999_p2 : select_ln16_29_reg_1397);

assign select_ln16_31_fu_1027_p3 = ((tmp_30_fu_1014_p3[0:0] == 1'b1) ? add_ln16_29_fu_1021_p2 : zext_ln16_4_fu_1010_p1);

assign select_ln16_3_fu_426_p3 = ((tmp_2_fu_412_p3[0:0] == 1'b1) ? add_ln16_1_fu_420_p2 : zext_ln16_1_fu_408_p1);

assign select_ln16_4_fu_448_p3 = ((tmp_3_fu_434_p3[0:0] == 1'b1) ? add_ln16_2_fu_442_p2 : select_ln16_3_fu_426_p3);

assign select_ln16_5_fu_670_p3 = ((tmp_4_reg_1214[0:0] == 1'b1) ? add_ln16_3_reg_1219 : select_ln16_4_reg_1209);

assign select_ln16_6_fu_681_p3 = ((tmp_5_reg_1224[0:0] == 1'b1) ? add_ln16_4_fu_675_p2 : select_ln16_5_fu_670_p3);

assign select_ln16_7_fu_698_p3 = ((tmp_6_reg_1229[0:0] == 1'b1) ? add_ln16_5_fu_692_p2 : zext_ln16_2_fu_688_p1);

assign select_ln16_8_fu_711_p3 = ((tmp_7_reg_1234[0:0] == 1'b1) ? add_ln16_6_fu_705_p2 : select_ln16_7_fu_698_p3);

assign select_ln16_9_fu_724_p3 = ((tmp_8_reg_1239_pp0_iter6_reg[0:0] == 1'b1) ? add_ln16_7_reg_1354 : select_ln16_8_reg_1349);

assign select_ln16_fu_366_p3 = ((trunc_ln16_fu_354_p1[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln39_1_fu_992_p3 = ((icmp_ln44_reg_1159_pp0_iter12_reg[0:0] == 1'b1) ? 10'd0 : popcount_acc_fu_152);

assign select_ln39_2_fu_293_p3 = ((icmp_ln44_fu_273_p2[0:0] == 1'b1) ? add_ln39_1_fu_287_p2 : ap_sig_allocacmp_i_load);

assign select_ln39_fu_279_p3 = ((icmp_ln44_fu_273_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j_load);

assign select_ln66_fu_1099_p3 = ((icmp_ln66_fu_1093_p2[0:0] == 1'b1) ? trunc_ln_cast_fu_1084_p4 : 7'd0);

assign shl_ln_fu_1045_p3 = {{popcount_acc_1_fu_1039_p2}, {1'd0}};

assign tmp_1_fu_386_p3 = xnor_res_fu_349_p2[32'd2];

assign tmp_2_fu_412_p3 = xnor_res_fu_349_p2[32'd3];

assign tmp_30_fu_1014_p3 = xnor_res_reg_1204_pp0_iter12_reg[32'd31];

assign tmp_3_fu_434_p3 = xnor_res_fu_349_p2[32'd4];

assign tmp_fu_358_p3 = xnor_res_fu_349_p2[32'd1];

assign trunc_ln16_fu_354_p1 = xnor_res_fu_349_p2[0:0];

assign trunc_ln_cast_fu_1084_p4 = {{grp_fu_1117_p3[14:8]}};

assign trunc_ln_fu_1075_p4 = {{grp_fu_1117_p3[15:8]}};

assign weights_l1_address0 = zext_ln46_fu_335_p1;

assign xnor_res_fu_349_p2 = (xor_ln49_fu_343_p2 ^ w_reg_1194);

assign xor_ln49_fu_343_p2 = (input_img_q0 ^ 32'd4294967295);

assign zext_ln16_1_fu_408_p1 = select_ln16_2_fu_400_p3;

assign zext_ln16_2_fu_688_p1 = select_ln16_6_fu_681_p3;

assign zext_ln16_3_fu_792_p1 = select_ln16_14_fu_785_p3;

assign zext_ln16_4_fu_1010_p1 = select_ln16_30_fu_1004_p3;

assign zext_ln16_fu_374_p1 = trunc_ln16_fu_354_p1;

assign zext_ln39_fu_946_p1 = select_ln39_2_reg_1170_pp0_iter11_reg;

assign zext_ln44_1_fu_339_p1 = select_ln39_reg_1164_pp0_iter3_reg;

assign zext_ln46_fu_335_p1 = grp_fu_1108_p3;

assign zext_ln52_fu_1035_p1 = select_ln16_31_fu_1027_p3;

endmodule //bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_44_1
