

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "9", "14"],
		"CDFG" : "bgn_inference",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "22427", "EstimateLatencyMax" : "22427",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_img", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79", "Port" : "input_img", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "prediction", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "weights_l1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79", "Port" : "weights_l1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "bn_scale", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79", "Port" : "bn_scale", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "bn_offset", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79", "Port" : "bn_offset", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "weights_l2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2_fu_93", "Port" : "weights_l2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "bias_l2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2_fu_93", "Port" : "bias_l2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.hidden_out_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79", "Parent" : "0", "Child" : ["3", "4", "5", "6", "7", "8"],
		"CDFG" : "bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16017", "EstimateLatencyMax" : "16017",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_img", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "hidden_out", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "weights_l1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bn_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bn_offset", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "LAYER1_VITIS_LOOP_46_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter16", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter16", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79.weights_l1_U", "Parent" : "2"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79.bn_scale_U", "Parent" : "2"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79.bn_offset_U", "Parent" : "2"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79.mac_muladd_10ns_5ns_5ns_14_4_1_U1", "Parent" : "2"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79.mac_muladd_11s_5ns_13s_16_4_1_U2", "Parent" : "2"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_46_1_fu_79.flow_control_loop_pipe_sequential_init_U", "Parent" : "2"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2_fu_93", "Parent" : "0", "Child" : ["10", "11", "12", "13"],
		"CDFG" : "bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6406", "EstimateLatencyMax" : "6406",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "hidden_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "class_idx_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "weights_l2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bias_l2", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "LAYER2_VITIS_LOOP_79_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2_fu_93.weights_l2_U", "Parent" : "9"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2_fu_93.bias_l2_U", "Parent" : "9"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2_fu_93.mac_muladd_7ns_6s_31s_31_4_1_U10", "Parent" : "9"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_79_2_fu_93.flow_control_loop_pipe_sequential_init_U", "Parent" : "9"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U", "Parent" : "0"}]}
