domain_path: E:\source\.ITA\FPGA\7.RAD\zc702_workspace\mnist_mlp_platform\export\mnist_mlp_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
