domain_path: E:\source\.ITA\FPGA\7.RAD\zc702_workspace\bgn_radiation_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: D:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
