// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_42_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_img_address0,
        input_img_ce0,
        input_img_q0,
        hidden_out_address0,
        hidden_out_ce0,
        hidden_out_we0,
        hidden_out_d0,
        grp_fu_113_p_din0,
        grp_fu_113_p_din1,
        grp_fu_113_p_opcode,
        grp_fu_113_p_dout0,
        grp_fu_113_p_ce,
        grp_fu_117_p_din0,
        grp_fu_117_p_din1,
        grp_fu_117_p_opcode,
        grp_fu_117_p_dout0,
        grp_fu_117_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] input_img_address0;
output   input_img_ce0;
input  [31:0] input_img_q0;
output  [6:0] hidden_out_address0;
output   hidden_out_ce0;
output   hidden_out_we0;
output  [31:0] hidden_out_d0;
output  [31:0] grp_fu_113_p_din0;
output  [31:0] grp_fu_113_p_din1;
output  [1:0] grp_fu_113_p_opcode;
input  [31:0] grp_fu_113_p_dout0;
output   grp_fu_113_p_ce;
output  [31:0] grp_fu_117_p_din0;
output  [31:0] grp_fu_117_p_din1;
output  [4:0] grp_fu_117_p_opcode;
input  [0:0] grp_fu_117_p_dout0;
output   grp_fu_117_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln38_fu_281_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [14:0] layer1_w_address0;
wire   [31:0] layer1_w_q0;
wire   [10:0] bn_mean_address0;
wire   [31:0] bn_mean_q0;
wire   [10:0] bn_var_address0;
wire   [31:0] bn_var_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln42_fu_299_p2;
reg   [0:0] icmp_ln42_reg_1170;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter1_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter2_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter3_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter4_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter5_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter6_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter7_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter8_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter9_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter10_reg;
reg   [0:0] icmp_ln42_reg_1170_pp0_iter11_reg;
wire   [4:0] select_ln38_fu_305_p3;
reg   [4:0] select_ln38_reg_1175;
reg   [4:0] select_ln38_reg_1175_pp0_iter1_reg;
reg   [4:0] select_ln38_reg_1175_pp0_iter2_reg;
wire   [7:0] select_ln38_2_fu_319_p3;
reg   [7:0] select_ln38_2_reg_1181;
reg   [7:0] select_ln38_2_reg_1181_pp0_iter1_reg;
reg   [7:0] select_ln38_2_reg_1181_pp0_iter2_reg;
reg   [7:0] select_ln38_2_reg_1181_pp0_iter3_reg;
wire   [0:0] icmp_ln42_1_fu_337_p2;
reg   [0:0] icmp_ln42_1_reg_1191;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter1_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter2_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter3_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter4_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter5_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter6_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter7_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter8_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter9_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter10_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter11_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter12_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter13_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter14_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter15_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter16_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter17_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter18_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter19_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter20_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter21_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter22_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter23_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter24_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter25_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter26_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter27_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter28_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter29_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter30_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter31_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter32_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter33_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter34_reg;
reg   [0:0] icmp_ln42_1_reg_1191_pp0_iter35_reg;
wire   [31:0] xnor_result_fu_381_p2;
reg   [31:0] xnor_result_reg_1210;
reg   [31:0] xnor_result_reg_1210_pp0_iter5_reg;
reg   [31:0] xnor_result_reg_1210_pp0_iter6_reg;
reg   [31:0] xnor_result_reg_1210_pp0_iter7_reg;
reg   [31:0] xnor_result_reg_1210_pp0_iter8_reg;
reg   [31:0] xnor_result_reg_1210_pp0_iter9_reg;
reg   [31:0] xnor_result_reg_1210_pp0_iter10_reg;
reg   [31:0] xnor_result_reg_1210_pp0_iter11_reg;
wire   [2:0] cnt_4_fu_459_p3;
reg   [2:0] cnt_4_reg_1215;
reg   [0:0] tmp_4_reg_1221;
reg   [0:0] tmp_5_reg_1226;
reg   [0:0] tmp_6_reg_1231;
reg   [0:0] tmp_7_reg_1236;
reg   [0:0] tmp_8_reg_1241;
reg   [0:0] tmp_8_reg_1241_pp0_iter5_reg;
reg   [0:0] tmp_9_reg_1246;
reg   [0:0] tmp_9_reg_1246_pp0_iter5_reg;
reg   [0:0] tmp_10_reg_1251;
reg   [0:0] tmp_10_reg_1251_pp0_iter5_reg;
reg   [0:0] tmp_11_reg_1256;
reg   [0:0] tmp_11_reg_1256_pp0_iter5_reg;
reg   [0:0] tmp_12_reg_1261;
reg   [0:0] tmp_12_reg_1261_pp0_iter5_reg;
reg   [0:0] tmp_12_reg_1261_pp0_iter6_reg;
reg   [0:0] tmp_13_reg_1266;
reg   [0:0] tmp_13_reg_1266_pp0_iter5_reg;
reg   [0:0] tmp_13_reg_1266_pp0_iter6_reg;
reg   [0:0] tmp_14_reg_1271;
reg   [0:0] tmp_14_reg_1271_pp0_iter5_reg;
reg   [0:0] tmp_14_reg_1271_pp0_iter6_reg;
reg   [0:0] tmp_15_reg_1276;
reg   [0:0] tmp_15_reg_1276_pp0_iter5_reg;
reg   [0:0] tmp_15_reg_1276_pp0_iter6_reg;
reg   [0:0] tmp_15_reg_1276_pp0_iter7_reg;
reg   [0:0] tmp_16_reg_1281;
reg   [0:0] tmp_16_reg_1281_pp0_iter5_reg;
reg   [0:0] tmp_16_reg_1281_pp0_iter6_reg;
reg   [0:0] tmp_16_reg_1281_pp0_iter7_reg;
reg   [0:0] tmp_17_reg_1286;
reg   [0:0] tmp_17_reg_1286_pp0_iter5_reg;
reg   [0:0] tmp_17_reg_1286_pp0_iter6_reg;
reg   [0:0] tmp_17_reg_1286_pp0_iter7_reg;
reg   [0:0] tmp_18_reg_1291;
reg   [0:0] tmp_18_reg_1291_pp0_iter5_reg;
reg   [0:0] tmp_18_reg_1291_pp0_iter6_reg;
reg   [0:0] tmp_18_reg_1291_pp0_iter7_reg;
reg   [0:0] tmp_19_reg_1296;
reg   [0:0] tmp_19_reg_1296_pp0_iter5_reg;
reg   [0:0] tmp_19_reg_1296_pp0_iter6_reg;
reg   [0:0] tmp_19_reg_1296_pp0_iter7_reg;
reg   [0:0] tmp_19_reg_1296_pp0_iter8_reg;
reg   [0:0] tmp_20_reg_1301;
reg   [0:0] tmp_20_reg_1301_pp0_iter5_reg;
reg   [0:0] tmp_20_reg_1301_pp0_iter6_reg;
reg   [0:0] tmp_20_reg_1301_pp0_iter7_reg;
reg   [0:0] tmp_20_reg_1301_pp0_iter8_reg;
reg   [0:0] tmp_21_reg_1306;
reg   [0:0] tmp_21_reg_1306_pp0_iter5_reg;
reg   [0:0] tmp_21_reg_1306_pp0_iter6_reg;
reg   [0:0] tmp_21_reg_1306_pp0_iter7_reg;
reg   [0:0] tmp_21_reg_1306_pp0_iter8_reg;
reg   [0:0] tmp_22_reg_1311;
reg   [0:0] tmp_22_reg_1311_pp0_iter5_reg;
reg   [0:0] tmp_22_reg_1311_pp0_iter6_reg;
reg   [0:0] tmp_22_reg_1311_pp0_iter7_reg;
reg   [0:0] tmp_22_reg_1311_pp0_iter8_reg;
reg   [0:0] tmp_22_reg_1311_pp0_iter9_reg;
reg   [0:0] tmp_23_reg_1316;
reg   [0:0] tmp_23_reg_1316_pp0_iter5_reg;
reg   [0:0] tmp_23_reg_1316_pp0_iter6_reg;
reg   [0:0] tmp_23_reg_1316_pp0_iter7_reg;
reg   [0:0] tmp_23_reg_1316_pp0_iter8_reg;
reg   [0:0] tmp_23_reg_1316_pp0_iter9_reg;
reg   [0:0] tmp_24_reg_1321;
reg   [0:0] tmp_24_reg_1321_pp0_iter5_reg;
reg   [0:0] tmp_24_reg_1321_pp0_iter6_reg;
reg   [0:0] tmp_24_reg_1321_pp0_iter7_reg;
reg   [0:0] tmp_24_reg_1321_pp0_iter8_reg;
reg   [0:0] tmp_24_reg_1321_pp0_iter9_reg;
reg   [0:0] tmp_25_reg_1326;
reg   [0:0] tmp_25_reg_1326_pp0_iter5_reg;
reg   [0:0] tmp_25_reg_1326_pp0_iter6_reg;
reg   [0:0] tmp_25_reg_1326_pp0_iter7_reg;
reg   [0:0] tmp_25_reg_1326_pp0_iter8_reg;
reg   [0:0] tmp_25_reg_1326_pp0_iter9_reg;
reg   [0:0] tmp_26_reg_1331;
reg   [0:0] tmp_26_reg_1331_pp0_iter5_reg;
reg   [0:0] tmp_26_reg_1331_pp0_iter6_reg;
reg   [0:0] tmp_26_reg_1331_pp0_iter7_reg;
reg   [0:0] tmp_26_reg_1331_pp0_iter8_reg;
reg   [0:0] tmp_26_reg_1331_pp0_iter9_reg;
reg   [0:0] tmp_26_reg_1331_pp0_iter10_reg;
reg   [0:0] tmp_27_reg_1336;
reg   [0:0] tmp_27_reg_1336_pp0_iter5_reg;
reg   [0:0] tmp_27_reg_1336_pp0_iter6_reg;
reg   [0:0] tmp_27_reg_1336_pp0_iter7_reg;
reg   [0:0] tmp_27_reg_1336_pp0_iter8_reg;
reg   [0:0] tmp_27_reg_1336_pp0_iter9_reg;
reg   [0:0] tmp_27_reg_1336_pp0_iter10_reg;
reg   [0:0] tmp_28_reg_1341;
reg   [0:0] tmp_28_reg_1341_pp0_iter5_reg;
reg   [0:0] tmp_28_reg_1341_pp0_iter6_reg;
reg   [0:0] tmp_28_reg_1341_pp0_iter7_reg;
reg   [0:0] tmp_28_reg_1341_pp0_iter8_reg;
reg   [0:0] tmp_28_reg_1341_pp0_iter9_reg;
reg   [0:0] tmp_28_reg_1341_pp0_iter10_reg;
reg   [0:0] tmp_29_reg_1346;
reg   [0:0] tmp_29_reg_1346_pp0_iter5_reg;
reg   [0:0] tmp_29_reg_1346_pp0_iter6_reg;
reg   [0:0] tmp_29_reg_1346_pp0_iter7_reg;
reg   [0:0] tmp_29_reg_1346_pp0_iter8_reg;
reg   [0:0] tmp_29_reg_1346_pp0_iter9_reg;
reg   [0:0] tmp_29_reg_1346_pp0_iter10_reg;
reg   [0:0] tmp_29_reg_1346_pp0_iter11_reg;
reg   [0:0] tmp_30_reg_1351;
reg   [0:0] tmp_30_reg_1351_pp0_iter5_reg;
reg   [0:0] tmp_30_reg_1351_pp0_iter6_reg;
reg   [0:0] tmp_30_reg_1351_pp0_iter7_reg;
reg   [0:0] tmp_30_reg_1351_pp0_iter8_reg;
reg   [0:0] tmp_30_reg_1351_pp0_iter9_reg;
reg   [0:0] tmp_30_reg_1351_pp0_iter10_reg;
reg   [0:0] tmp_30_reg_1351_pp0_iter11_reg;
reg   [6:0] hidden_out_addr_reg_1366;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter5_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter6_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter7_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter8_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter9_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter10_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter11_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter12_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter13_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter14_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter15_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter16_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter17_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter18_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter19_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter20_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter21_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter22_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter23_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter24_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter25_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter26_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter27_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter28_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter29_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter30_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter31_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter32_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter33_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter34_reg;
reg   [6:0] hidden_out_addr_reg_1366_pp0_iter35_reg;
wire   [3:0] cnt_10_fu_730_p3;
reg   [3:0] cnt_10_reg_1371;
wire   [3:0] cnt_11_fu_737_p2;
reg   [3:0] cnt_11_reg_1376;
reg   [31:0] bn_mean_load_reg_1381;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter6_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter7_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter8_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter9_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter10_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter11_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter12_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter13_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter14_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter15_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter16_reg;
reg   [31:0] bn_mean_load_reg_1381_pp0_iter17_reg;
reg   [31:0] bn_var_load_reg_1386;
wire   [3:0] cnt_16_fu_780_p3;
reg   [3:0] cnt_16_reg_1391;
wire   [4:0] zext_ln12_3_fu_824_p1;
reg   [4:0] zext_ln12_3_reg_1397;
wire   [4:0] add_ln15_12_fu_828_p2;
reg   [4:0] add_ln15_12_reg_1402;
wire   [4:0] cnt_27_fu_871_p3;
reg   [4:0] cnt_27_reg_1407;
wire   [4:0] cnt_31_fu_908_p3;
reg   [4:0] cnt_31_reg_1413;
wire   [4:0] cnt_32_fu_915_p2;
reg   [4:0] cnt_32_reg_1418;
wire   [4:0] cnt_37_fu_958_p3;
reg   [4:0] cnt_37_reg_1423;
reg   [31:0] x_assign_reg_1429;
wire   [4:0] cnt_42_fu_995_p3;
reg   [4:0] cnt_42_reg_1434;
wire   [4:0] add_ln15_26_fu_1002_p2;
reg   [4:0] add_ln15_26_reg_1439;
wire   [9:0] total_popcount_1_fu_1065_p2;
reg   [9:0] total_popcount_1_reg_1444;
wire   [31:0] grp_fu_245_p1;
reg   [31:0] conv_reg_1454;
wire   [31:0] grp_fu_237_p2;
reg   [31:0] sub_reg_1459;
wire   [31:0] grp_fu_253_p2;
reg   [31:0] tmp_reg_1464;
wire   [31:0] grp_fu_241_p2;
reg   [31:0] val_reg_1469;
reg   [31:0] val_reg_1469_pp0_iter35_reg;
wire   [63:0] zext_ln44_fu_365_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln42_1_fu_361_p1;
wire   [63:0] zext_ln38_fu_369_p1;
reg   [9:0] total_popcount_fu_152;
wire    ap_loop_init;
reg   [4:0] j_fu_156;
wire   [4:0] add_ln42_fu_331_p2;
reg   [4:0] ap_sig_allocacmp_j_load;
reg   [7:0] i_fu_160;
reg   [7:0] ap_sig_allocacmp_i_load;
reg   [11:0] indvar_flatten_fu_164;
wire   [11:0] add_ln38_fu_287_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
reg    layer1_w_ce0_local;
reg    input_img_ce0_local;
reg    bn_mean_ce0_local;
reg    bn_var_ce0_local;
reg    hidden_out_we0_local;
wire   [31:0] select_ln54_fu_1121_p3;
reg    hidden_out_ce0_local;
wire   [31:0] grp_fu_245_p0;
wire   [7:0] add_ln38_1_fu_313_p2;
wire   [11:0] grp_fu_1129_p3;
wire   [31:0] xor_ln48_fu_375_p2;
wire   [0:0] cnt_fu_387_p1;
wire   [0:0] tmp_1_fu_395_p3;
wire   [1:0] select_ln15_fu_403_p3;
wire   [1:0] zext_ln12_fu_391_p1;
wire   [1:0] cnt_1_fu_411_p3;
wire   [0:0] tmp_2_fu_419_p3;
wire   [1:0] cnt_2_fu_427_p2;
wire   [1:0] cnt_3_fu_433_p3;
wire   [2:0] zext_ln12_1_fu_441_p1;
wire   [0:0] tmp_3_fu_445_p3;
wire   [2:0] add_ln15_fu_453_p2;
wire   [2:0] cnt_5_fu_683_p2;
wire   [2:0] cnt_6_fu_688_p3;
wire   [2:0] add_ln15_2_fu_694_p2;
wire   [2:0] cnt_7_fu_700_p3;
wire   [2:0] cnt_8_fu_707_p2;
wire   [2:0] cnt_9_fu_713_p3;
wire   [3:0] zext_ln12_2_fu_720_p1;
wire   [3:0] add_ln15_4_fu_724_p2;
wire   [3:0] cnt_12_fu_743_p3;
wire   [3:0] add_ln15_6_fu_748_p2;
wire   [3:0] cnt_13_fu_754_p3;
wire   [3:0] cnt_14_fu_761_p2;
wire   [3:0] cnt_15_fu_767_p3;
wire   [3:0] add_ln15_8_fu_774_p2;
wire   [3:0] cnt_17_fu_787_p2;
wire   [3:0] cnt_18_fu_792_p3;
wire   [3:0] add_ln15_10_fu_798_p2;
wire   [3:0] cnt_19_fu_804_p3;
wire   [3:0] cnt_20_fu_811_p2;
wire   [3:0] cnt_21_fu_817_p3;
wire   [4:0] cnt_22_fu_834_p3;
wire   [4:0] cnt_23_fu_839_p2;
wire   [4:0] cnt_24_fu_845_p3;
wire   [4:0] add_ln15_14_fu_852_p2;
wire   [4:0] cnt_25_fu_858_p3;
wire   [4:0] cnt_26_fu_865_p2;
wire   [4:0] add_ln15_16_fu_878_p2;
wire   [4:0] cnt_28_fu_883_p3;
wire   [4:0] cnt_29_fu_889_p2;
wire   [4:0] cnt_30_fu_895_p3;
wire   [4:0] add_ln15_18_fu_902_p2;
wire   [4:0] cnt_33_fu_921_p3;
wire   [4:0] add_ln15_20_fu_926_p2;
wire   [4:0] cnt_34_fu_932_p3;
wire   [4:0] cnt_35_fu_939_p2;
wire   [4:0] cnt_36_fu_945_p3;
wire   [4:0] add_ln15_22_fu_952_p2;
wire   [4:0] cnt_38_fu_965_p2;
wire   [4:0] cnt_39_fu_970_p3;
wire   [4:0] add_ln15_24_fu_976_p2;
wire   [4:0] cnt_40_fu_982_p3;
wire   [4:0] cnt_41_fu_989_p2;
wire   [4:0] cnt_43_fu_1018_p3;
wire   [4:0] cnt_44_fu_1023_p2;
wire   [4:0] cnt_45_fu_1029_p3;
wire   [5:0] zext_ln12_4_fu_1036_p1;
wire   [0:0] tmp_33_fu_1040_p3;
wire   [5:0] add_ln15_28_fu_1047_p2;
wire   [5:0] cnt_46_fu_1053_p3;
wire   [9:0] zext_ln12_5_fu_1061_p1;
wire   [9:0] select_ln38_1_fu_1011_p3;
wire   [31:0] bitcast_ln54_fu_1080_p1;
wire   [7:0] tmp_s_fu_1083_p4;
wire   [22:0] trunc_ln54_fu_1093_p1;
wire   [0:0] icmp_ln54_1_fu_1103_p2;
wire   [0:0] icmp_ln54_fu_1097_p2;
wire   [0:0] or_ln54_fu_1109_p2;
wire   [0:0] and_ln54_fu_1115_p2;
wire   [7:0] grp_fu_1129_p0;
wire   [4:0] grp_fu_1129_p1;
wire   [4:0] grp_fu_1129_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [11:0] grp_fu_1129_p00;
wire   [11:0] grp_fu_1129_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 total_popcount_fu_152 = 10'd0;
#0 j_fu_156 = 5'd0;
#0 i_fu_160 = 8'd0;
#0 indvar_flatten_fu_164 = 12'd0;
#0 ap_done_reg = 1'b0;
end

bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_42_1_layer1_w_ROM_1P_BRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 32000 ),
    .AddressWidth( 15 ))
layer1_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer1_w_address0),
    .ce0(layer1_w_ce0_local),
    .q0(layer1_w_q0)
);

bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_42_1_bn_mean_ROM_1P_BRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
bn_mean_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bn_mean_address0),
    .ce0(bn_mean_ce0_local),
    .q0(bn_mean_q0)
);

bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_42_1_bn_var_ROM_1P_BRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
bn_var_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bn_var_address0),
    .ce0(bn_var_ce0_local),
    .q0(bn_var_q0)
);

bgn_inference_fsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_5_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv_reg_1454),
    .din1(bn_mean_load_reg_1381_pp0_iter17_reg),
    .ce(1'b1),
    .dout(grp_fu_237_p2)
);

bgn_inference_fdiv_32ns_32ns_32_12_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_12_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_reg_1459),
    .din1(tmp_reg_1464),
    .ce(1'b1),
    .dout(grp_fu_241_p2)
);

bgn_inference_sitofp_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_5_no_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_245_p0),
    .ce(1'b1),
    .dout(grp_fu_245_p1)
);

bgn_inference_fsqrt_32ns_32ns_32_12_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsqrt_32ns_32ns_32_12_no_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(x_assign_reg_1429),
    .ce(1'b1),
    .dout(grp_fu_253_p2)
);

bgn_inference_mac_muladd_8ns_5ns_5ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mac_muladd_8ns_5ns_5ns_12_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1129_p0),
    .din1(grp_fu_1129_p1),
    .din2(grp_fu_1129_p2),
    .ce(1'b1),
    .dout(grp_fu_1129_p3)
);

bgn_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter35_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln38_fu_281_p2 == 1'd0))) begin
            i_fu_160 <= select_ln38_2_fu_319_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_160 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln38_fu_281_p2 == 1'd0))) begin
            indvar_flatten_fu_164 <= add_ln38_fu_287_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_164 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln38_fu_281_p2 == 1'd0))) begin
            j_fu_156 <= add_ln42_fu_331_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_156 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            total_popcount_fu_152 <= 10'd0;
        end else if ((ap_enable_reg_pp0_iter12 == 1'b1)) begin
            total_popcount_fu_152 <= total_popcount_1_fu_1065_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln15_12_reg_1402 <= add_ln15_12_fu_828_p2;
        add_ln15_26_reg_1439 <= add_ln15_26_fu_1002_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        bn_mean_load_reg_1381 <= bn_mean_q0;
        bn_mean_load_reg_1381_pp0_iter10_reg <= bn_mean_load_reg_1381_pp0_iter9_reg;
        bn_mean_load_reg_1381_pp0_iter11_reg <= bn_mean_load_reg_1381_pp0_iter10_reg;
        bn_mean_load_reg_1381_pp0_iter12_reg <= bn_mean_load_reg_1381_pp0_iter11_reg;
        bn_mean_load_reg_1381_pp0_iter13_reg <= bn_mean_load_reg_1381_pp0_iter12_reg;
        bn_mean_load_reg_1381_pp0_iter14_reg <= bn_mean_load_reg_1381_pp0_iter13_reg;
        bn_mean_load_reg_1381_pp0_iter15_reg <= bn_mean_load_reg_1381_pp0_iter14_reg;
        bn_mean_load_reg_1381_pp0_iter16_reg <= bn_mean_load_reg_1381_pp0_iter15_reg;
        bn_mean_load_reg_1381_pp0_iter17_reg <= bn_mean_load_reg_1381_pp0_iter16_reg;
        bn_mean_load_reg_1381_pp0_iter6_reg <= bn_mean_load_reg_1381;
        bn_mean_load_reg_1381_pp0_iter7_reg <= bn_mean_load_reg_1381_pp0_iter6_reg;
        bn_mean_load_reg_1381_pp0_iter8_reg <= bn_mean_load_reg_1381_pp0_iter7_reg;
        bn_mean_load_reg_1381_pp0_iter9_reg <= bn_mean_load_reg_1381_pp0_iter8_reg;
        bn_var_load_reg_1386 <= bn_var_q0;
        cnt_10_reg_1371 <= cnt_10_fu_730_p3;
        cnt_11_reg_1376 <= cnt_11_fu_737_p2;
        cnt_16_reg_1391 <= cnt_16_fu_780_p3;
        cnt_27_reg_1407 <= cnt_27_fu_871_p3;
        cnt_31_reg_1413 <= cnt_31_fu_908_p3;
        cnt_32_reg_1418 <= cnt_32_fu_915_p2;
        cnt_37_reg_1423 <= cnt_37_fu_958_p3;
        cnt_42_reg_1434 <= cnt_42_fu_995_p3;
        cnt_4_reg_1215 <= cnt_4_fu_459_p3;
        conv_reg_1454 <= grp_fu_245_p1;
        hidden_out_addr_reg_1366 <= zext_ln38_fu_369_p1;
        hidden_out_addr_reg_1366_pp0_iter10_reg <= hidden_out_addr_reg_1366_pp0_iter9_reg;
        hidden_out_addr_reg_1366_pp0_iter11_reg <= hidden_out_addr_reg_1366_pp0_iter10_reg;
        hidden_out_addr_reg_1366_pp0_iter12_reg <= hidden_out_addr_reg_1366_pp0_iter11_reg;
        hidden_out_addr_reg_1366_pp0_iter13_reg <= hidden_out_addr_reg_1366_pp0_iter12_reg;
        hidden_out_addr_reg_1366_pp0_iter14_reg <= hidden_out_addr_reg_1366_pp0_iter13_reg;
        hidden_out_addr_reg_1366_pp0_iter15_reg <= hidden_out_addr_reg_1366_pp0_iter14_reg;
        hidden_out_addr_reg_1366_pp0_iter16_reg <= hidden_out_addr_reg_1366_pp0_iter15_reg;
        hidden_out_addr_reg_1366_pp0_iter17_reg <= hidden_out_addr_reg_1366_pp0_iter16_reg;
        hidden_out_addr_reg_1366_pp0_iter18_reg <= hidden_out_addr_reg_1366_pp0_iter17_reg;
        hidden_out_addr_reg_1366_pp0_iter19_reg <= hidden_out_addr_reg_1366_pp0_iter18_reg;
        hidden_out_addr_reg_1366_pp0_iter20_reg <= hidden_out_addr_reg_1366_pp0_iter19_reg;
        hidden_out_addr_reg_1366_pp0_iter21_reg <= hidden_out_addr_reg_1366_pp0_iter20_reg;
        hidden_out_addr_reg_1366_pp0_iter22_reg <= hidden_out_addr_reg_1366_pp0_iter21_reg;
        hidden_out_addr_reg_1366_pp0_iter23_reg <= hidden_out_addr_reg_1366_pp0_iter22_reg;
        hidden_out_addr_reg_1366_pp0_iter24_reg <= hidden_out_addr_reg_1366_pp0_iter23_reg;
        hidden_out_addr_reg_1366_pp0_iter25_reg <= hidden_out_addr_reg_1366_pp0_iter24_reg;
        hidden_out_addr_reg_1366_pp0_iter26_reg <= hidden_out_addr_reg_1366_pp0_iter25_reg;
        hidden_out_addr_reg_1366_pp0_iter27_reg <= hidden_out_addr_reg_1366_pp0_iter26_reg;
        hidden_out_addr_reg_1366_pp0_iter28_reg <= hidden_out_addr_reg_1366_pp0_iter27_reg;
        hidden_out_addr_reg_1366_pp0_iter29_reg <= hidden_out_addr_reg_1366_pp0_iter28_reg;
        hidden_out_addr_reg_1366_pp0_iter30_reg <= hidden_out_addr_reg_1366_pp0_iter29_reg;
        hidden_out_addr_reg_1366_pp0_iter31_reg <= hidden_out_addr_reg_1366_pp0_iter30_reg;
        hidden_out_addr_reg_1366_pp0_iter32_reg <= hidden_out_addr_reg_1366_pp0_iter31_reg;
        hidden_out_addr_reg_1366_pp0_iter33_reg <= hidden_out_addr_reg_1366_pp0_iter32_reg;
        hidden_out_addr_reg_1366_pp0_iter34_reg <= hidden_out_addr_reg_1366_pp0_iter33_reg;
        hidden_out_addr_reg_1366_pp0_iter35_reg <= hidden_out_addr_reg_1366_pp0_iter34_reg;
        hidden_out_addr_reg_1366_pp0_iter5_reg <= hidden_out_addr_reg_1366;
        hidden_out_addr_reg_1366_pp0_iter6_reg <= hidden_out_addr_reg_1366_pp0_iter5_reg;
        hidden_out_addr_reg_1366_pp0_iter7_reg <= hidden_out_addr_reg_1366_pp0_iter6_reg;
        hidden_out_addr_reg_1366_pp0_iter8_reg <= hidden_out_addr_reg_1366_pp0_iter7_reg;
        hidden_out_addr_reg_1366_pp0_iter9_reg <= hidden_out_addr_reg_1366_pp0_iter8_reg;
        icmp_ln42_1_reg_1191_pp0_iter10_reg <= icmp_ln42_1_reg_1191_pp0_iter9_reg;
        icmp_ln42_1_reg_1191_pp0_iter11_reg <= icmp_ln42_1_reg_1191_pp0_iter10_reg;
        icmp_ln42_1_reg_1191_pp0_iter12_reg <= icmp_ln42_1_reg_1191_pp0_iter11_reg;
        icmp_ln42_1_reg_1191_pp0_iter13_reg <= icmp_ln42_1_reg_1191_pp0_iter12_reg;
        icmp_ln42_1_reg_1191_pp0_iter14_reg <= icmp_ln42_1_reg_1191_pp0_iter13_reg;
        icmp_ln42_1_reg_1191_pp0_iter15_reg <= icmp_ln42_1_reg_1191_pp0_iter14_reg;
        icmp_ln42_1_reg_1191_pp0_iter16_reg <= icmp_ln42_1_reg_1191_pp0_iter15_reg;
        icmp_ln42_1_reg_1191_pp0_iter17_reg <= icmp_ln42_1_reg_1191_pp0_iter16_reg;
        icmp_ln42_1_reg_1191_pp0_iter18_reg <= icmp_ln42_1_reg_1191_pp0_iter17_reg;
        icmp_ln42_1_reg_1191_pp0_iter19_reg <= icmp_ln42_1_reg_1191_pp0_iter18_reg;
        icmp_ln42_1_reg_1191_pp0_iter20_reg <= icmp_ln42_1_reg_1191_pp0_iter19_reg;
        icmp_ln42_1_reg_1191_pp0_iter21_reg <= icmp_ln42_1_reg_1191_pp0_iter20_reg;
        icmp_ln42_1_reg_1191_pp0_iter22_reg <= icmp_ln42_1_reg_1191_pp0_iter21_reg;
        icmp_ln42_1_reg_1191_pp0_iter23_reg <= icmp_ln42_1_reg_1191_pp0_iter22_reg;
        icmp_ln42_1_reg_1191_pp0_iter24_reg <= icmp_ln42_1_reg_1191_pp0_iter23_reg;
        icmp_ln42_1_reg_1191_pp0_iter25_reg <= icmp_ln42_1_reg_1191_pp0_iter24_reg;
        icmp_ln42_1_reg_1191_pp0_iter26_reg <= icmp_ln42_1_reg_1191_pp0_iter25_reg;
        icmp_ln42_1_reg_1191_pp0_iter27_reg <= icmp_ln42_1_reg_1191_pp0_iter26_reg;
        icmp_ln42_1_reg_1191_pp0_iter28_reg <= icmp_ln42_1_reg_1191_pp0_iter27_reg;
        icmp_ln42_1_reg_1191_pp0_iter29_reg <= icmp_ln42_1_reg_1191_pp0_iter28_reg;
        icmp_ln42_1_reg_1191_pp0_iter2_reg <= icmp_ln42_1_reg_1191_pp0_iter1_reg;
        icmp_ln42_1_reg_1191_pp0_iter30_reg <= icmp_ln42_1_reg_1191_pp0_iter29_reg;
        icmp_ln42_1_reg_1191_pp0_iter31_reg <= icmp_ln42_1_reg_1191_pp0_iter30_reg;
        icmp_ln42_1_reg_1191_pp0_iter32_reg <= icmp_ln42_1_reg_1191_pp0_iter31_reg;
        icmp_ln42_1_reg_1191_pp0_iter33_reg <= icmp_ln42_1_reg_1191_pp0_iter32_reg;
        icmp_ln42_1_reg_1191_pp0_iter34_reg <= icmp_ln42_1_reg_1191_pp0_iter33_reg;
        icmp_ln42_1_reg_1191_pp0_iter35_reg <= icmp_ln42_1_reg_1191_pp0_iter34_reg;
        icmp_ln42_1_reg_1191_pp0_iter3_reg <= icmp_ln42_1_reg_1191_pp0_iter2_reg;
        icmp_ln42_1_reg_1191_pp0_iter4_reg <= icmp_ln42_1_reg_1191_pp0_iter3_reg;
        icmp_ln42_1_reg_1191_pp0_iter5_reg <= icmp_ln42_1_reg_1191_pp0_iter4_reg;
        icmp_ln42_1_reg_1191_pp0_iter6_reg <= icmp_ln42_1_reg_1191_pp0_iter5_reg;
        icmp_ln42_1_reg_1191_pp0_iter7_reg <= icmp_ln42_1_reg_1191_pp0_iter6_reg;
        icmp_ln42_1_reg_1191_pp0_iter8_reg <= icmp_ln42_1_reg_1191_pp0_iter7_reg;
        icmp_ln42_1_reg_1191_pp0_iter9_reg <= icmp_ln42_1_reg_1191_pp0_iter8_reg;
        icmp_ln42_reg_1170_pp0_iter10_reg <= icmp_ln42_reg_1170_pp0_iter9_reg;
        icmp_ln42_reg_1170_pp0_iter11_reg <= icmp_ln42_reg_1170_pp0_iter10_reg;
        icmp_ln42_reg_1170_pp0_iter2_reg <= icmp_ln42_reg_1170_pp0_iter1_reg;
        icmp_ln42_reg_1170_pp0_iter3_reg <= icmp_ln42_reg_1170_pp0_iter2_reg;
        icmp_ln42_reg_1170_pp0_iter4_reg <= icmp_ln42_reg_1170_pp0_iter3_reg;
        icmp_ln42_reg_1170_pp0_iter5_reg <= icmp_ln42_reg_1170_pp0_iter4_reg;
        icmp_ln42_reg_1170_pp0_iter6_reg <= icmp_ln42_reg_1170_pp0_iter5_reg;
        icmp_ln42_reg_1170_pp0_iter7_reg <= icmp_ln42_reg_1170_pp0_iter6_reg;
        icmp_ln42_reg_1170_pp0_iter8_reg <= icmp_ln42_reg_1170_pp0_iter7_reg;
        icmp_ln42_reg_1170_pp0_iter9_reg <= icmp_ln42_reg_1170_pp0_iter8_reg;
        select_ln38_2_reg_1181_pp0_iter2_reg <= select_ln38_2_reg_1181_pp0_iter1_reg;
        select_ln38_2_reg_1181_pp0_iter3_reg <= select_ln38_2_reg_1181_pp0_iter2_reg;
        select_ln38_reg_1175_pp0_iter2_reg <= select_ln38_reg_1175_pp0_iter1_reg;
        sub_reg_1459 <= grp_fu_237_p2;
        tmp_10_reg_1251 <= xnor_result_fu_381_p2[32'd10];
        tmp_10_reg_1251_pp0_iter5_reg <= tmp_10_reg_1251;
        tmp_11_reg_1256 <= xnor_result_fu_381_p2[32'd11];
        tmp_11_reg_1256_pp0_iter5_reg <= tmp_11_reg_1256;
        tmp_12_reg_1261 <= xnor_result_fu_381_p2[32'd12];
        tmp_12_reg_1261_pp0_iter5_reg <= tmp_12_reg_1261;
        tmp_12_reg_1261_pp0_iter6_reg <= tmp_12_reg_1261_pp0_iter5_reg;
        tmp_13_reg_1266 <= xnor_result_fu_381_p2[32'd13];
        tmp_13_reg_1266_pp0_iter5_reg <= tmp_13_reg_1266;
        tmp_13_reg_1266_pp0_iter6_reg <= tmp_13_reg_1266_pp0_iter5_reg;
        tmp_14_reg_1271 <= xnor_result_fu_381_p2[32'd14];
        tmp_14_reg_1271_pp0_iter5_reg <= tmp_14_reg_1271;
        tmp_14_reg_1271_pp0_iter6_reg <= tmp_14_reg_1271_pp0_iter5_reg;
        tmp_15_reg_1276 <= xnor_result_fu_381_p2[32'd15];
        tmp_15_reg_1276_pp0_iter5_reg <= tmp_15_reg_1276;
        tmp_15_reg_1276_pp0_iter6_reg <= tmp_15_reg_1276_pp0_iter5_reg;
        tmp_15_reg_1276_pp0_iter7_reg <= tmp_15_reg_1276_pp0_iter6_reg;
        tmp_16_reg_1281 <= xnor_result_fu_381_p2[32'd16];
        tmp_16_reg_1281_pp0_iter5_reg <= tmp_16_reg_1281;
        tmp_16_reg_1281_pp0_iter6_reg <= tmp_16_reg_1281_pp0_iter5_reg;
        tmp_16_reg_1281_pp0_iter7_reg <= tmp_16_reg_1281_pp0_iter6_reg;
        tmp_17_reg_1286 <= xnor_result_fu_381_p2[32'd17];
        tmp_17_reg_1286_pp0_iter5_reg <= tmp_17_reg_1286;
        tmp_17_reg_1286_pp0_iter6_reg <= tmp_17_reg_1286_pp0_iter5_reg;
        tmp_17_reg_1286_pp0_iter7_reg <= tmp_17_reg_1286_pp0_iter6_reg;
        tmp_18_reg_1291 <= xnor_result_fu_381_p2[32'd18];
        tmp_18_reg_1291_pp0_iter5_reg <= tmp_18_reg_1291;
        tmp_18_reg_1291_pp0_iter6_reg <= tmp_18_reg_1291_pp0_iter5_reg;
        tmp_18_reg_1291_pp0_iter7_reg <= tmp_18_reg_1291_pp0_iter6_reg;
        tmp_19_reg_1296 <= xnor_result_fu_381_p2[32'd19];
        tmp_19_reg_1296_pp0_iter5_reg <= tmp_19_reg_1296;
        tmp_19_reg_1296_pp0_iter6_reg <= tmp_19_reg_1296_pp0_iter5_reg;
        tmp_19_reg_1296_pp0_iter7_reg <= tmp_19_reg_1296_pp0_iter6_reg;
        tmp_19_reg_1296_pp0_iter8_reg <= tmp_19_reg_1296_pp0_iter7_reg;
        tmp_20_reg_1301 <= xnor_result_fu_381_p2[32'd20];
        tmp_20_reg_1301_pp0_iter5_reg <= tmp_20_reg_1301;
        tmp_20_reg_1301_pp0_iter6_reg <= tmp_20_reg_1301_pp0_iter5_reg;
        tmp_20_reg_1301_pp0_iter7_reg <= tmp_20_reg_1301_pp0_iter6_reg;
        tmp_20_reg_1301_pp0_iter8_reg <= tmp_20_reg_1301_pp0_iter7_reg;
        tmp_21_reg_1306 <= xnor_result_fu_381_p2[32'd21];
        tmp_21_reg_1306_pp0_iter5_reg <= tmp_21_reg_1306;
        tmp_21_reg_1306_pp0_iter6_reg <= tmp_21_reg_1306_pp0_iter5_reg;
        tmp_21_reg_1306_pp0_iter7_reg <= tmp_21_reg_1306_pp0_iter6_reg;
        tmp_21_reg_1306_pp0_iter8_reg <= tmp_21_reg_1306_pp0_iter7_reg;
        tmp_22_reg_1311 <= xnor_result_fu_381_p2[32'd22];
        tmp_22_reg_1311_pp0_iter5_reg <= tmp_22_reg_1311;
        tmp_22_reg_1311_pp0_iter6_reg <= tmp_22_reg_1311_pp0_iter5_reg;
        tmp_22_reg_1311_pp0_iter7_reg <= tmp_22_reg_1311_pp0_iter6_reg;
        tmp_22_reg_1311_pp0_iter8_reg <= tmp_22_reg_1311_pp0_iter7_reg;
        tmp_22_reg_1311_pp0_iter9_reg <= tmp_22_reg_1311_pp0_iter8_reg;
        tmp_23_reg_1316 <= xnor_result_fu_381_p2[32'd23];
        tmp_23_reg_1316_pp0_iter5_reg <= tmp_23_reg_1316;
        tmp_23_reg_1316_pp0_iter6_reg <= tmp_23_reg_1316_pp0_iter5_reg;
        tmp_23_reg_1316_pp0_iter7_reg <= tmp_23_reg_1316_pp0_iter6_reg;
        tmp_23_reg_1316_pp0_iter8_reg <= tmp_23_reg_1316_pp0_iter7_reg;
        tmp_23_reg_1316_pp0_iter9_reg <= tmp_23_reg_1316_pp0_iter8_reg;
        tmp_24_reg_1321 <= xnor_result_fu_381_p2[32'd24];
        tmp_24_reg_1321_pp0_iter5_reg <= tmp_24_reg_1321;
        tmp_24_reg_1321_pp0_iter6_reg <= tmp_24_reg_1321_pp0_iter5_reg;
        tmp_24_reg_1321_pp0_iter7_reg <= tmp_24_reg_1321_pp0_iter6_reg;
        tmp_24_reg_1321_pp0_iter8_reg <= tmp_24_reg_1321_pp0_iter7_reg;
        tmp_24_reg_1321_pp0_iter9_reg <= tmp_24_reg_1321_pp0_iter8_reg;
        tmp_25_reg_1326 <= xnor_result_fu_381_p2[32'd25];
        tmp_25_reg_1326_pp0_iter5_reg <= tmp_25_reg_1326;
        tmp_25_reg_1326_pp0_iter6_reg <= tmp_25_reg_1326_pp0_iter5_reg;
        tmp_25_reg_1326_pp0_iter7_reg <= tmp_25_reg_1326_pp0_iter6_reg;
        tmp_25_reg_1326_pp0_iter8_reg <= tmp_25_reg_1326_pp0_iter7_reg;
        tmp_25_reg_1326_pp0_iter9_reg <= tmp_25_reg_1326_pp0_iter8_reg;
        tmp_26_reg_1331 <= xnor_result_fu_381_p2[32'd26];
        tmp_26_reg_1331_pp0_iter10_reg <= tmp_26_reg_1331_pp0_iter9_reg;
        tmp_26_reg_1331_pp0_iter5_reg <= tmp_26_reg_1331;
        tmp_26_reg_1331_pp0_iter6_reg <= tmp_26_reg_1331_pp0_iter5_reg;
        tmp_26_reg_1331_pp0_iter7_reg <= tmp_26_reg_1331_pp0_iter6_reg;
        tmp_26_reg_1331_pp0_iter8_reg <= tmp_26_reg_1331_pp0_iter7_reg;
        tmp_26_reg_1331_pp0_iter9_reg <= tmp_26_reg_1331_pp0_iter8_reg;
        tmp_27_reg_1336 <= xnor_result_fu_381_p2[32'd27];
        tmp_27_reg_1336_pp0_iter10_reg <= tmp_27_reg_1336_pp0_iter9_reg;
        tmp_27_reg_1336_pp0_iter5_reg <= tmp_27_reg_1336;
        tmp_27_reg_1336_pp0_iter6_reg <= tmp_27_reg_1336_pp0_iter5_reg;
        tmp_27_reg_1336_pp0_iter7_reg <= tmp_27_reg_1336_pp0_iter6_reg;
        tmp_27_reg_1336_pp0_iter8_reg <= tmp_27_reg_1336_pp0_iter7_reg;
        tmp_27_reg_1336_pp0_iter9_reg <= tmp_27_reg_1336_pp0_iter8_reg;
        tmp_28_reg_1341 <= xnor_result_fu_381_p2[32'd28];
        tmp_28_reg_1341_pp0_iter10_reg <= tmp_28_reg_1341_pp0_iter9_reg;
        tmp_28_reg_1341_pp0_iter5_reg <= tmp_28_reg_1341;
        tmp_28_reg_1341_pp0_iter6_reg <= tmp_28_reg_1341_pp0_iter5_reg;
        tmp_28_reg_1341_pp0_iter7_reg <= tmp_28_reg_1341_pp0_iter6_reg;
        tmp_28_reg_1341_pp0_iter8_reg <= tmp_28_reg_1341_pp0_iter7_reg;
        tmp_28_reg_1341_pp0_iter9_reg <= tmp_28_reg_1341_pp0_iter8_reg;
        tmp_29_reg_1346 <= xnor_result_fu_381_p2[32'd29];
        tmp_29_reg_1346_pp0_iter10_reg <= tmp_29_reg_1346_pp0_iter9_reg;
        tmp_29_reg_1346_pp0_iter11_reg <= tmp_29_reg_1346_pp0_iter10_reg;
        tmp_29_reg_1346_pp0_iter5_reg <= tmp_29_reg_1346;
        tmp_29_reg_1346_pp0_iter6_reg <= tmp_29_reg_1346_pp0_iter5_reg;
        tmp_29_reg_1346_pp0_iter7_reg <= tmp_29_reg_1346_pp0_iter6_reg;
        tmp_29_reg_1346_pp0_iter8_reg <= tmp_29_reg_1346_pp0_iter7_reg;
        tmp_29_reg_1346_pp0_iter9_reg <= tmp_29_reg_1346_pp0_iter8_reg;
        tmp_30_reg_1351 <= xnor_result_fu_381_p2[32'd30];
        tmp_30_reg_1351_pp0_iter10_reg <= tmp_30_reg_1351_pp0_iter9_reg;
        tmp_30_reg_1351_pp0_iter11_reg <= tmp_30_reg_1351_pp0_iter10_reg;
        tmp_30_reg_1351_pp0_iter5_reg <= tmp_30_reg_1351;
        tmp_30_reg_1351_pp0_iter6_reg <= tmp_30_reg_1351_pp0_iter5_reg;
        tmp_30_reg_1351_pp0_iter7_reg <= tmp_30_reg_1351_pp0_iter6_reg;
        tmp_30_reg_1351_pp0_iter8_reg <= tmp_30_reg_1351_pp0_iter7_reg;
        tmp_30_reg_1351_pp0_iter9_reg <= tmp_30_reg_1351_pp0_iter8_reg;
        tmp_4_reg_1221 <= xnor_result_fu_381_p2[32'd4];
        tmp_5_reg_1226 <= xnor_result_fu_381_p2[32'd5];
        tmp_6_reg_1231 <= xnor_result_fu_381_p2[32'd6];
        tmp_7_reg_1236 <= xnor_result_fu_381_p2[32'd7];
        tmp_8_reg_1241 <= xnor_result_fu_381_p2[32'd8];
        tmp_8_reg_1241_pp0_iter5_reg <= tmp_8_reg_1241;
        tmp_9_reg_1246 <= xnor_result_fu_381_p2[32'd9];
        tmp_9_reg_1246_pp0_iter5_reg <= tmp_9_reg_1246;
        tmp_reg_1464 <= grp_fu_253_p2;
        total_popcount_1_reg_1444 <= total_popcount_1_fu_1065_p2;
        val_reg_1469 <= grp_fu_241_p2;
        val_reg_1469_pp0_iter35_reg <= val_reg_1469;
        x_assign_reg_1429 <= grp_fu_113_p_dout0;
        xnor_result_reg_1210 <= xnor_result_fu_381_p2;
        xnor_result_reg_1210_pp0_iter10_reg <= xnor_result_reg_1210_pp0_iter9_reg;
        xnor_result_reg_1210_pp0_iter11_reg <= xnor_result_reg_1210_pp0_iter10_reg;
        xnor_result_reg_1210_pp0_iter5_reg <= xnor_result_reg_1210;
        xnor_result_reg_1210_pp0_iter6_reg <= xnor_result_reg_1210_pp0_iter5_reg;
        xnor_result_reg_1210_pp0_iter7_reg <= xnor_result_reg_1210_pp0_iter6_reg;
        xnor_result_reg_1210_pp0_iter8_reg <= xnor_result_reg_1210_pp0_iter7_reg;
        xnor_result_reg_1210_pp0_iter9_reg <= xnor_result_reg_1210_pp0_iter8_reg;
        zext_ln12_3_reg_1397[3 : 0] <= zext_ln12_3_fu_824_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln42_1_reg_1191 <= icmp_ln42_1_fu_337_p2;
        icmp_ln42_1_reg_1191_pp0_iter1_reg <= icmp_ln42_1_reg_1191;
        icmp_ln42_reg_1170 <= icmp_ln42_fu_299_p2;
        icmp_ln42_reg_1170_pp0_iter1_reg <= icmp_ln42_reg_1170;
        select_ln38_2_reg_1181 <= select_ln38_2_fu_319_p3;
        select_ln38_2_reg_1181_pp0_iter1_reg <= select_ln38_2_reg_1181;
        select_ln38_reg_1175 <= select_ln38_fu_305_p3;
        select_ln38_reg_1175_pp0_iter1_reg <= select_ln38_reg_1175;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln38_fu_281_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter35_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) 
    & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_160;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_164;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 5'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_156;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bn_mean_ce0_local = 1'b1;
    end else begin
        bn_mean_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bn_var_ce0_local = 1'b1;
    end else begin
        bn_var_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter36 == 1'b1))) begin
        hidden_out_ce0_local = 1'b1;
    end else begin
        hidden_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln42_1_reg_1191_pp0_iter35_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter36 == 1'b1))) begin
        hidden_out_we0_local = 1'b1;
    end else begin
        hidden_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_img_ce0_local = 1'b1;
    end else begin
        input_img_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer1_w_ce0_local = 1'b1;
    end else begin
        layer1_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_10_fu_798_p2 = (cnt_18_fu_792_p3 + 4'd1);

assign add_ln15_12_fu_828_p2 = (zext_ln12_3_fu_824_p1 + 5'd1);

assign add_ln15_14_fu_852_p2 = (cnt_24_fu_845_p3 + 5'd1);

assign add_ln15_16_fu_878_p2 = (cnt_27_reg_1407 + 5'd1);

assign add_ln15_18_fu_902_p2 = (cnt_30_fu_895_p3 + 5'd1);

assign add_ln15_20_fu_926_p2 = (cnt_33_fu_921_p3 + 5'd1);

assign add_ln15_22_fu_952_p2 = (cnt_36_fu_945_p3 + 5'd1);

assign add_ln15_24_fu_976_p2 = (cnt_39_fu_970_p3 + 5'd1);

assign add_ln15_26_fu_1002_p2 = (cnt_42_fu_995_p3 + 5'd1);

assign add_ln15_28_fu_1047_p2 = (zext_ln12_4_fu_1036_p1 + 6'd1);

assign add_ln15_2_fu_694_p2 = (cnt_6_fu_688_p3 + 3'd1);

assign add_ln15_4_fu_724_p2 = (zext_ln12_2_fu_720_p1 + 4'd1);

assign add_ln15_6_fu_748_p2 = (cnt_12_fu_743_p3 + 4'd1);

assign add_ln15_8_fu_774_p2 = (cnt_15_fu_767_p3 + 4'd1);

assign add_ln15_fu_453_p2 = (zext_ln12_1_fu_441_p1 + 3'd1);

assign add_ln38_1_fu_313_p2 = (ap_sig_allocacmp_i_load + 8'd1);

assign add_ln38_fu_287_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln42_fu_331_p2 = (select_ln38_fu_305_p3 + 5'd1);

assign and_ln54_fu_1115_p2 = (or_ln54_fu_1109_p2 & grp_fu_117_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln54_fu_1080_p1 = val_reg_1469_pp0_iter35_reg;

assign bn_mean_address0 = zext_ln38_fu_369_p1;

assign bn_var_address0 = zext_ln38_fu_369_p1;

assign cnt_10_fu_730_p3 = ((tmp_7_reg_1236[0:0] == 1'b1) ? add_ln15_4_fu_724_p2 : zext_ln12_2_fu_720_p1);

assign cnt_11_fu_737_p2 = (cnt_10_fu_730_p3 + 4'd1);

assign cnt_12_fu_743_p3 = ((tmp_8_reg_1241_pp0_iter5_reg[0:0] == 1'b1) ? cnt_11_reg_1376 : cnt_10_reg_1371);

assign cnt_13_fu_754_p3 = ((tmp_9_reg_1246_pp0_iter5_reg[0:0] == 1'b1) ? add_ln15_6_fu_748_p2 : cnt_12_fu_743_p3);

assign cnt_14_fu_761_p2 = (cnt_13_fu_754_p3 + 4'd1);

assign cnt_15_fu_767_p3 = ((tmp_10_reg_1251_pp0_iter5_reg[0:0] == 1'b1) ? cnt_14_fu_761_p2 : cnt_13_fu_754_p3);

assign cnt_16_fu_780_p3 = ((tmp_11_reg_1256_pp0_iter5_reg[0:0] == 1'b1) ? add_ln15_8_fu_774_p2 : cnt_15_fu_767_p3);

assign cnt_17_fu_787_p2 = (cnt_16_reg_1391 + 4'd1);

assign cnt_18_fu_792_p3 = ((tmp_12_reg_1261_pp0_iter6_reg[0:0] == 1'b1) ? cnt_17_fu_787_p2 : cnt_16_reg_1391);

assign cnt_19_fu_804_p3 = ((tmp_13_reg_1266_pp0_iter6_reg[0:0] == 1'b1) ? add_ln15_10_fu_798_p2 : cnt_18_fu_792_p3);

assign cnt_1_fu_411_p3 = ((tmp_1_fu_395_p3[0:0] == 1'b1) ? select_ln15_fu_403_p3 : zext_ln12_fu_391_p1);

assign cnt_20_fu_811_p2 = (cnt_19_fu_804_p3 + 4'd1);

assign cnt_21_fu_817_p3 = ((tmp_14_reg_1271_pp0_iter6_reg[0:0] == 1'b1) ? cnt_20_fu_811_p2 : cnt_19_fu_804_p3);

assign cnt_22_fu_834_p3 = ((tmp_15_reg_1276_pp0_iter7_reg[0:0] == 1'b1) ? add_ln15_12_reg_1402 : zext_ln12_3_reg_1397);

assign cnt_23_fu_839_p2 = (cnt_22_fu_834_p3 + 5'd1);

assign cnt_24_fu_845_p3 = ((tmp_16_reg_1281_pp0_iter7_reg[0:0] == 1'b1) ? cnt_23_fu_839_p2 : cnt_22_fu_834_p3);

assign cnt_25_fu_858_p3 = ((tmp_17_reg_1286_pp0_iter7_reg[0:0] == 1'b1) ? add_ln15_14_fu_852_p2 : cnt_24_fu_845_p3);

assign cnt_26_fu_865_p2 = (cnt_25_fu_858_p3 + 5'd1);

assign cnt_27_fu_871_p3 = ((tmp_18_reg_1291_pp0_iter7_reg[0:0] == 1'b1) ? cnt_26_fu_865_p2 : cnt_25_fu_858_p3);

assign cnt_28_fu_883_p3 = ((tmp_19_reg_1296_pp0_iter8_reg[0:0] == 1'b1) ? add_ln15_16_fu_878_p2 : cnt_27_reg_1407);

assign cnt_29_fu_889_p2 = (cnt_28_fu_883_p3 + 5'd1);

assign cnt_2_fu_427_p2 = (cnt_1_fu_411_p3 + 2'd1);

assign cnt_30_fu_895_p3 = ((tmp_20_reg_1301_pp0_iter8_reg[0:0] == 1'b1) ? cnt_29_fu_889_p2 : cnt_28_fu_883_p3);

assign cnt_31_fu_908_p3 = ((tmp_21_reg_1306_pp0_iter8_reg[0:0] == 1'b1) ? add_ln15_18_fu_902_p2 : cnt_30_fu_895_p3);

assign cnt_32_fu_915_p2 = (cnt_31_fu_908_p3 + 5'd1);

assign cnt_33_fu_921_p3 = ((tmp_22_reg_1311_pp0_iter9_reg[0:0] == 1'b1) ? cnt_32_reg_1418 : cnt_31_reg_1413);

assign cnt_34_fu_932_p3 = ((tmp_23_reg_1316_pp0_iter9_reg[0:0] == 1'b1) ? add_ln15_20_fu_926_p2 : cnt_33_fu_921_p3);

assign cnt_35_fu_939_p2 = (cnt_34_fu_932_p3 + 5'd1);

assign cnt_36_fu_945_p3 = ((tmp_24_reg_1321_pp0_iter9_reg[0:0] == 1'b1) ? cnt_35_fu_939_p2 : cnt_34_fu_932_p3);

assign cnt_37_fu_958_p3 = ((tmp_25_reg_1326_pp0_iter9_reg[0:0] == 1'b1) ? add_ln15_22_fu_952_p2 : cnt_36_fu_945_p3);

assign cnt_38_fu_965_p2 = (cnt_37_reg_1423 + 5'd1);

assign cnt_39_fu_970_p3 = ((tmp_26_reg_1331_pp0_iter10_reg[0:0] == 1'b1) ? cnt_38_fu_965_p2 : cnt_37_reg_1423);

assign cnt_3_fu_433_p3 = ((tmp_2_fu_419_p3[0:0] == 1'b1) ? cnt_2_fu_427_p2 : cnt_1_fu_411_p3);

assign cnt_40_fu_982_p3 = ((tmp_27_reg_1336_pp0_iter10_reg[0:0] == 1'b1) ? add_ln15_24_fu_976_p2 : cnt_39_fu_970_p3);

assign cnt_41_fu_989_p2 = (cnt_40_fu_982_p3 + 5'd1);

assign cnt_42_fu_995_p3 = ((tmp_28_reg_1341_pp0_iter10_reg[0:0] == 1'b1) ? cnt_41_fu_989_p2 : cnt_40_fu_982_p3);

assign cnt_43_fu_1018_p3 = ((tmp_29_reg_1346_pp0_iter11_reg[0:0] == 1'b1) ? add_ln15_26_reg_1439 : cnt_42_reg_1434);

assign cnt_44_fu_1023_p2 = (cnt_43_fu_1018_p3 + 5'd1);

assign cnt_45_fu_1029_p3 = ((tmp_30_reg_1351_pp0_iter11_reg[0:0] == 1'b1) ? cnt_44_fu_1023_p2 : cnt_43_fu_1018_p3);

assign cnt_46_fu_1053_p3 = ((tmp_33_fu_1040_p3[0:0] == 1'b1) ? add_ln15_28_fu_1047_p2 : zext_ln12_4_fu_1036_p1);

assign cnt_4_fu_459_p3 = ((tmp_3_fu_445_p3[0:0] == 1'b1) ? add_ln15_fu_453_p2 : zext_ln12_1_fu_441_p1);

assign cnt_5_fu_683_p2 = (cnt_4_reg_1215 + 3'd1);

assign cnt_6_fu_688_p3 = ((tmp_4_reg_1221[0:0] == 1'b1) ? cnt_5_fu_683_p2 : cnt_4_reg_1215);

assign cnt_7_fu_700_p3 = ((tmp_5_reg_1226[0:0] == 1'b1) ? add_ln15_2_fu_694_p2 : cnt_6_fu_688_p3);

assign cnt_8_fu_707_p2 = (cnt_7_fu_700_p3 + 3'd1);

assign cnt_9_fu_713_p3 = ((tmp_6_reg_1231[0:0] == 1'b1) ? cnt_8_fu_707_p2 : cnt_7_fu_700_p3);

assign cnt_fu_387_p1 = xnor_result_fu_381_p2[0:0];

assign grp_fu_1129_p0 = grp_fu_1129_p00;

assign grp_fu_1129_p00 = select_ln38_2_fu_319_p3;

assign grp_fu_1129_p1 = 12'd25;

assign grp_fu_1129_p2 = grp_fu_1129_p20;

assign grp_fu_1129_p20 = select_ln38_reg_1175_pp0_iter1_reg;

assign grp_fu_113_p_ce = 1'b1;

assign grp_fu_113_p_din0 = bn_var_load_reg_1386;

assign grp_fu_113_p_din1 = 32'd925353388;

assign grp_fu_113_p_opcode = 2'd0;

assign grp_fu_117_p_ce = 1'b1;

assign grp_fu_117_p_din0 = val_reg_1469;

assign grp_fu_117_p_din1 = 32'd0;

assign grp_fu_117_p_opcode = 5'd2;

assign grp_fu_245_p0 = total_popcount_1_reg_1444;

assign hidden_out_address0 = hidden_out_addr_reg_1366_pp0_iter35_reg;

assign hidden_out_ce0 = hidden_out_ce0_local;

assign hidden_out_d0 = select_ln54_fu_1121_p3;

assign hidden_out_we0 = hidden_out_we0_local;

assign icmp_ln38_fu_281_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd3200) ? 1'b1 : 1'b0);

assign icmp_ln42_1_fu_337_p2 = ((add_ln42_fu_331_p2 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_299_p2 = ((ap_sig_allocacmp_j_load == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln54_1_fu_1103_p2 = ((trunc_ln54_fu_1093_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_1097_p2 = ((tmp_s_fu_1083_p4 != 8'd255) ? 1'b1 : 1'b0);

assign input_img_address0 = zext_ln42_1_fu_361_p1;

assign input_img_ce0 = input_img_ce0_local;

assign layer1_w_address0 = zext_ln44_fu_365_p1;

assign or_ln54_fu_1109_p2 = (icmp_ln54_fu_1097_p2 | icmp_ln54_1_fu_1103_p2);

assign select_ln15_fu_403_p3 = ((cnt_fu_387_p1[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln38_1_fu_1011_p3 = ((icmp_ln42_reg_1170_pp0_iter11_reg[0:0] == 1'b1) ? 10'd0 : total_popcount_fu_152);

assign select_ln38_2_fu_319_p3 = ((icmp_ln42_fu_299_p2[0:0] == 1'b1) ? add_ln38_1_fu_313_p2 : ap_sig_allocacmp_i_load);

assign select_ln38_fu_305_p3 = ((icmp_ln42_fu_299_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j_load);

assign select_ln54_fu_1121_p3 = ((and_ln54_fu_1115_p2[0:0] == 1'b1) ? val_reg_1469_pp0_iter35_reg : 32'd0);

assign tmp_1_fu_395_p3 = xnor_result_fu_381_p2[32'd1];

assign tmp_2_fu_419_p3 = xnor_result_fu_381_p2[32'd2];

assign tmp_33_fu_1040_p3 = xnor_result_reg_1210_pp0_iter11_reg[32'd31];

assign tmp_3_fu_445_p3 = xnor_result_fu_381_p2[32'd3];

assign tmp_s_fu_1083_p4 = {{bitcast_ln54_fu_1080_p1[30:23]}};

assign total_popcount_1_fu_1065_p2 = (zext_ln12_5_fu_1061_p1 + select_ln38_1_fu_1011_p3);

assign trunc_ln54_fu_1093_p1 = bitcast_ln54_fu_1080_p1[22:0];

assign xnor_result_fu_381_p2 = (xor_ln48_fu_375_p2 ^ layer1_w_q0);

assign xor_ln48_fu_375_p2 = (input_img_q0 ^ 32'd4294967295);

assign zext_ln12_1_fu_441_p1 = cnt_3_fu_433_p3;

assign zext_ln12_2_fu_720_p1 = cnt_9_fu_713_p3;

assign zext_ln12_3_fu_824_p1 = cnt_21_fu_817_p3;

assign zext_ln12_4_fu_1036_p1 = cnt_45_fu_1029_p3;

assign zext_ln12_5_fu_1061_p1 = cnt_46_fu_1053_p3;

assign zext_ln12_fu_391_p1 = cnt_fu_387_p1;

assign zext_ln38_fu_369_p1 = select_ln38_2_reg_1181_pp0_iter3_reg;

assign zext_ln42_1_fu_361_p1 = select_ln38_reg_1175_pp0_iter2_reg;

assign zext_ln44_fu_365_p1 = grp_fu_1129_p3;

always @ (posedge ap_clk) begin
    zext_ln12_3_reg_1397[4] <= 1'b0;
end

endmodule //bgn_inference_bgn_inference_Pipeline_LAYER1_VITIS_LOOP_42_1
