domain_path: C:\source\.ITA\FPGA\25.2\6.IA\zc702_workspace\mnist_mlp_bgn_p\export\mnist_mlp_bgn_p\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
