# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# Block Designs: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/bd_44e3_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/bd_44e3_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_29/bd_44e3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_30/bd_44e3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_31/bd_44e3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_32/bd_44e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_34/bd_44e3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_35/bd_44e3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_36/bd_44e3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_37/bd_44e3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_38/bd_44e3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_39/bd_44e3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_bgn_inference_0_4/system_bgn_inference_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bgn_inference_0_4 || ORIG_REF_NAME==system_bgn_inference_0_4} -quiet] -quiet

# IP: bd/system/ip/system_bgn_inference_0_bram_0/system_bgn_inference_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bgn_inference_0_bram_0 || ORIG_REF_NAME==system_bgn_inference_0_bram_0} -quiet] -quiet

# IP: bd/system/ip/system_radiation_injector_0_1/system_radiation_injector_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_radiation_injector_0_1 || ORIG_REF_NAME==system_radiation_injector_0_1} -quiet] -quiet

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arinsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rinsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awinsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_winsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_binsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_aroutsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_routsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/bd_44e3_awoutsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_woutsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_boutsw_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_arni_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_rni_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_awni_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/bd_44e3_wni_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_bni_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_s00a2s_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_sarn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_srn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_sawn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_swn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_sbn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_m00s2a_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_m00arn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_m00rn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_29/bd_44e3_m00awn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_30/bd_44e3_m00wn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_31/bd_44e3_m00bn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_m01s2a_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_34/bd_44e3_m01arn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_35/bd_44e3_m01rn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_36/bd_44e3_m01awn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_37/bd_44e3_m01wn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_38/bd_44e3_m01bn_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_bgn_inference_0_4/constraints/bgn_inference_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_bgn_inference_0_bram_0/system_bgn_inference_0_bram_0_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/ip/system_radiation_injector_0_1/constraints/radiation_injector_ooc.xdc

# XDC: e:/source/.ITA/FPGA/7.RAD/zc702/zc702.gen/sources_1/bd/system/system_ooc.xdc
