// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bgn_inference_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_64_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hidden_out_address0,
        hidden_out_ce0,
        hidden_out_q0,
        class_idx_23_out,
        class_idx_23_out_ap_vld,
        grp_fu_113_p_din0,
        grp_fu_113_p_din1,
        grp_fu_113_p_opcode,
        grp_fu_113_p_dout0,
        grp_fu_113_p_ce,
        grp_fu_117_p_din0,
        grp_fu_117_p_din1,
        grp_fu_117_p_opcode,
        grp_fu_117_p_dout0,
        grp_fu_117_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] hidden_out_address0;
output   hidden_out_ce0;
input  [31:0] hidden_out_q0;
output  [31:0] class_idx_23_out;
output   class_idx_23_out_ap_vld;
output  [31:0] grp_fu_113_p_din0;
output  [31:0] grp_fu_113_p_din1;
output  [1:0] grp_fu_113_p_opcode;
input  [31:0] grp_fu_113_p_dout0;
output   grp_fu_113_p_ce;
output  [31:0] grp_fu_117_p_din0;
output  [31:0] grp_fu_117_p_din1;
output  [4:0] grp_fu_117_p_opcode;
input  [0:0] grp_fu_117_p_dout0;
output   grp_fu_117_p_ce;

reg ap_idle;
reg class_idx_23_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln61_reg_510;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [13:0] layer2_w_address0;
wire   [31:0] layer2_w_q0;
wire   [3:0] layer2_b_address0;
wire   [31:0] layer2_b_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln61_fu_189_p2;
reg   [0:0] icmp_ln61_reg_510_pp0_iter1_reg;
wire   [0:0] icmp_ln64_fu_204_p2;
reg   [0:0] icmp_ln64_reg_514;
reg   [0:0] icmp_ln64_reg_514_pp0_iter1_reg;
reg   [0:0] icmp_ln64_reg_514_pp0_iter2_reg;
wire   [7:0] select_ln59_fu_210_p3;
reg   [7:0] select_ln59_reg_521;
wire   [0:0] first_iter_1_fu_218_p2;
reg   [0:0] first_iter_1_reg_526;
reg   [0:0] first_iter_1_reg_526_pp0_iter1_reg;
wire   [3:0] select_ln61_fu_254_p3;
reg   [3:0] select_ln61_reg_535;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [3:0] select_ln61_reg_535_pp0_iter1_reg;
reg   [3:0] select_ln61_reg_535_pp0_iter2_reg;
reg   [31:0] hidden_out_load_reg_541;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] sum_reg_561;
wire   [31:0] grp_fu_152_p2;
reg   [31:0] mul_reg_566;
reg   [31:0] sum_2_reg_576;
wire   [31:0] select_ln61_1_fu_311_p3;
reg   [31:0] select_ln61_1_reg_583;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln64_fu_224_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln66_fu_278_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln61_fu_288_p1;
reg   [7:0] j_fu_70;
wire   [7:0] add_ln64_fu_229_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_j_load;
reg   [31:0] max_val_12_fu_74;
wire   [31:0] max_val_1_fu_430_p3;
wire    ap_block_pp0_stage3;
reg   [31:0] class_idx_23_fu_78;
wire   [31:0] class_idx_2_fu_422_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage0;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [31:0] class_idx_fu_82;
wire   [31:0] select_ln61_2_fu_330_p3;
reg   [31:0] max_val_fu_86;
reg   [3:0] class_idx_1_fu_90;
reg   [10:0] indvar_flatten9_fu_94;
wire   [10:0] add_ln61_fu_195_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten9_load;
reg   [31:0] sum_1_fu_98;
reg   [31:0] ap_sig_allocacmp_sum_1_load;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage0_01001;
reg    hidden_out_ce0_local;
reg    layer2_w_ce0_local;
reg    layer2_b_ce0_local;
wire   [3:0] add_ln61_1_fu_248_p2;
wire   [10:0] zext_ln64_1_fu_269_p1;
wire   [10:0] tmp_s_fu_261_p3;
wire   [10:0] add_ln66_fu_272_p2;
wire   [31:0] bitcast_ln69_fu_337_p1;
wire   [31:0] bitcast_ln69_1_fu_354_p1;
wire   [7:0] tmp_1_fu_340_p4;
wire   [22:0] trunc_ln69_fu_350_p1;
wire   [0:0] icmp_ln69_1_fu_377_p2;
wire   [0:0] icmp_ln69_fu_371_p2;
wire   [7:0] tmp_2_fu_357_p4;
wire   [22:0] trunc_ln69_1_fu_367_p1;
wire   [0:0] icmp_ln69_3_fu_395_p2;
wire   [0:0] icmp_ln69_2_fu_389_p2;
wire   [0:0] or_ln69_1_fu_401_p2;
wire   [0:0] and_ln69_fu_407_p2;
wire   [0:0] or_ln69_fu_383_p2;
wire   [0:0] and_ln69_1_fu_413_p2;
wire   [31:0] zext_ln69_fu_419_p1;
wire    ap_block_pp0_stage3_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_block_pp0_stage2_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 j_fu_70 = 8'd0;
#0 max_val_12_fu_74 = 32'd0;
#0 class_idx_23_fu_78 = 32'd0;
#0 class_idx_fu_82 = 32'd0;
#0 max_val_fu_86 = 32'd0;
#0 class_idx_1_fu_90 = 4'd0;
#0 indvar_flatten9_fu_94 = 11'd0;
#0 sum_1_fu_98 = 32'd0;
#0 ap_done_reg = 1'b0;
end

bgn_inference_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_64_2_layer2_w_ROM_1P_BRAM_1R #(
    .DataWidth( 32 ),
    .AddressRange( 12800 ),
    .AddressWidth( 14 ))
layer2_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer2_w_address0),
    .ce0(layer2_w_ce0_local),
    .q0(layer2_w_q0)
);

bgn_inference_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_64_2_layer2_b_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer2_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer2_b_address0),
    .ce0(layer2_b_ce0_local),
    .q0(layer2_b_q0)
);

bgn_inference_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(hidden_out_load_reg_541),
    .din1(layer2_w_q0),
    .ce(1'b1),
    .dout(grp_fu_152_p2)
);

bgn_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        class_idx_1_fu_90 <= 4'd0;
    end else if (((icmp_ln61_reg_510 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        class_idx_1_fu_90 <= select_ln61_fu_254_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            class_idx_fu_82 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            class_idx_fu_82 <= select_ln61_2_fu_330_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln61_fu_189_p2 == 1'd0))) begin
            indvar_flatten9_fu_94 <= add_ln61_fu_195_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten9_fu_94 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln61_fu_189_p2 == 1'd0))) begin
            j_fu_70 <= add_ln64_fu_229_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_70 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        max_val_fu_86 <= 32'd3323740160;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        max_val_fu_86 <= select_ln61_1_fu_311_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (first_iter_1_reg_526_pp0_iter1_reg == 1'd1))) begin
            sum_1_fu_98 <= sum_reg_561;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            sum_1_fu_98 <= grp_fu_113_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        class_idx_23_fu_78 <= class_idx_2_fu_422_p3;
        max_val_12_fu_74 <= max_val_1_fu_430_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_iter_1_reg_526 <= first_iter_1_fu_218_p2;
        first_iter_1_reg_526_pp0_iter1_reg <= first_iter_1_reg_526;
        icmp_ln61_reg_510 <= icmp_ln61_fu_189_p2;
        icmp_ln61_reg_510_pp0_iter1_reg <= icmp_ln61_reg_510;
        icmp_ln64_reg_514 <= icmp_ln64_fu_204_p2;
        icmp_ln64_reg_514_pp0_iter1_reg <= icmp_ln64_reg_514;
        icmp_ln64_reg_514_pp0_iter2_reg <= icmp_ln64_reg_514_pp0_iter1_reg;
        select_ln59_reg_521 <= select_ln59_fu_210_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hidden_out_load_reg_541 <= hidden_out_q0;
        mul_reg_566 <= grp_fu_152_p2;
        select_ln61_reg_535 <= select_ln61_fu_254_p3;
        select_ln61_reg_535_pp0_iter1_reg <= select_ln61_reg_535;
        select_ln61_reg_535_pp0_iter2_reg <= select_ln61_reg_535_pp0_iter1_reg;
        sum_reg_561 <= layer2_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        select_ln61_1_reg_583 <= select_ln61_1_fu_311_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_2_reg_576 <= grp_fu_113_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln61_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln61_reg_510_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten9_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten9_load = indvar_flatten9_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 8'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (first_iter_1_reg_526_pp0_iter1_reg == 1'd1))) begin
            ap_sig_allocacmp_sum_1_load = sum_reg_561;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            ap_sig_allocacmp_sum_1_load = grp_fu_113_p_dout0;
        end else begin
            ap_sig_allocacmp_sum_1_load = sum_1_fu_98;
        end
    end else begin
        ap_sig_allocacmp_sum_1_load = sum_1_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln61_reg_510_pp0_iter1_reg == 1'd1))) begin
        class_idx_23_out_ap_vld = 1'b1;
    end else begin
        class_idx_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hidden_out_ce0_local = 1'b1;
    end else begin
        hidden_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_b_ce0_local = 1'b1;
    end else begin
        layer2_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer2_w_ce0_local = 1'b1;
    end else begin
        layer2_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln61_1_fu_248_p2 = (class_idx_1_fu_90 + 4'd1);

assign add_ln61_fu_195_p2 = (ap_sig_allocacmp_indvar_flatten9_load + 11'd1);

assign add_ln64_fu_229_p2 = (select_ln59_fu_210_p3 + 8'd1);

assign add_ln66_fu_272_p2 = (zext_ln64_1_fu_269_p1 + tmp_s_fu_261_p3);

assign and_ln69_1_fu_413_p2 = (or_ln69_fu_383_p2 & and_ln69_fu_407_p2);

assign and_ln69_fu_407_p2 = (or_ln69_1_fu_401_p2 & grp_fu_117_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign bitcast_ln69_1_fu_354_p1 = select_ln61_1_reg_583;

assign bitcast_ln69_fu_337_p1 = sum_2_reg_576;

assign class_idx_23_out = class_idx_23_fu_78;

assign class_idx_2_fu_422_p3 = ((and_ln69_1_fu_413_p2[0:0] == 1'b1) ? zext_ln69_fu_419_p1 : select_ln61_2_fu_330_p3);

assign first_iter_1_fu_218_p2 = ((select_ln59_fu_210_p3 == 8'd0) ? 1'b1 : 1'b0);

assign grp_fu_113_p_ce = 1'b1;

assign grp_fu_113_p_din0 = ap_sig_allocacmp_sum_1_load;

assign grp_fu_113_p_din1 = mul_reg_566;

assign grp_fu_113_p_opcode = 2'd0;

assign grp_fu_117_p_ce = 1'b1;

assign grp_fu_117_p_din0 = sum_2_reg_576;

assign grp_fu_117_p_din1 = select_ln61_1_fu_311_p3;

assign grp_fu_117_p_opcode = 5'd2;

assign hidden_out_address0 = zext_ln64_fu_224_p1;

assign hidden_out_ce0 = hidden_out_ce0_local;

assign icmp_ln61_fu_189_p2 = ((ap_sig_allocacmp_indvar_flatten9_load == 11'd1280) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_204_p2 = ((ap_sig_allocacmp_j_load == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln69_1_fu_377_p2 = ((trunc_ln69_fu_350_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln69_2_fu_389_p2 = ((tmp_2_fu_357_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln69_3_fu_395_p2 = ((trunc_ln69_1_fu_367_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_371_p2 = ((tmp_1_fu_340_p4 != 8'd255) ? 1'b1 : 1'b0);

assign layer2_b_address0 = zext_ln61_fu_288_p1;

assign layer2_w_address0 = zext_ln66_fu_278_p1;

assign max_val_1_fu_430_p3 = ((and_ln69_1_fu_413_p2[0:0] == 1'b1) ? sum_2_reg_576 : select_ln61_1_reg_583);

assign or_ln69_1_fu_401_p2 = (icmp_ln69_3_fu_395_p2 | icmp_ln69_2_fu_389_p2);

assign or_ln69_fu_383_p2 = (icmp_ln69_fu_371_p2 | icmp_ln69_1_fu_377_p2);

assign select_ln59_fu_210_p3 = ((icmp_ln64_fu_204_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_j_load);

assign select_ln61_1_fu_311_p3 = ((icmp_ln64_reg_514_pp0_iter2_reg[0:0] == 1'b1) ? max_val_12_fu_74 : max_val_fu_86);

assign select_ln61_2_fu_330_p3 = ((icmp_ln64_reg_514_pp0_iter2_reg[0:0] == 1'b1) ? class_idx_23_fu_78 : class_idx_fu_82);

assign select_ln61_fu_254_p3 = ((icmp_ln64_reg_514[0:0] == 1'b1) ? add_ln61_1_fu_248_p2 : class_idx_1_fu_90);

assign tmp_1_fu_340_p4 = {{bitcast_ln69_fu_337_p1[30:23]}};

assign tmp_2_fu_357_p4 = {{bitcast_ln69_1_fu_354_p1[30:23]}};

assign tmp_s_fu_261_p3 = {{select_ln61_fu_254_p3}, {7'd0}};

assign trunc_ln69_1_fu_367_p1 = bitcast_ln69_1_fu_354_p1[22:0];

assign trunc_ln69_fu_350_p1 = bitcast_ln69_fu_337_p1[22:0];

assign zext_ln61_fu_288_p1 = select_ln61_reg_535;

assign zext_ln64_1_fu_269_p1 = select_ln59_reg_521;

assign zext_ln64_fu_224_p1 = select_ln59_fu_210_p3;

assign zext_ln66_fu_278_p1 = add_ln66_fu_272_p2;

assign zext_ln69_fu_419_p1 = select_ln61_reg_535_pp0_iter2_reg;

endmodule //bgn_inference_bgn_inference_Pipeline_LAYER2_VITIS_LOOP_64_2
