domain_path: E:\FPGA\2024\MicroPhase-Z7-Lite-Board\BGN\edt_zc702_workspace\plat_bgn\export\plat_bgn\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
