# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_bgn_inference_0_0/system_bgn_inference_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bgn_inference_0_0 || ORIG_REF_NAME==system_bgn_inference_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# Block Designs: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_0/bd_44e3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/bd_44e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_bgn_inference_0_0/constraints/bgn_inference_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_s00a2s_0_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_sarn_0_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_srn_0_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_sawn_0_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/bd_44e3_swn_0_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_sbn_0_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_m00s2a_0_ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/FPGA/2024/MicroPhase-Z7-Lite-Board/BGN/edt_zc702/edt_zc702.gen/sources_1/bd/system/system_ooc.xdc
